(function(){
'use strict';

const A={
 FWD:{label:'앞으로 달리기',icon:'→',kind:'action',concept:'순차'},
 BACK:{label:'한 칸 후퇴',icon:'←',kind:'action',concept:'이동'},
 JUMP:{label:'점프',icon:'⤴',kind:'action',concept:'행동'},
 HIGH_JUMP:{label:'높이 점프',icon:'⇈',kind:'action',concept:'행동'},
 DROP:{label:'아래로 내려가기',icon:'⇣',kind:'action',concept:'행동'},
 DASH:{label:'대시',icon:'»',kind:'action',concept:'행동'},
 DODGE:{label:'회피',icon:'↯',kind:'action',concept:'행동'},
 ATTACK:{label:'공격',icon:'⚔',kind:'action',concept:'행동'},
 WAIT:{label:'잠깐 기다리기',icon:'…',kind:'action',concept:'타이밍'},
 COLLECT:{label:'줍기',icon:'◆',kind:'action',concept:'변수'},
 OPEN:{label:'문 열기',icon:'▣',kind:'action',concept:'조건'},
 HEAL:{label:'회복',icon:'♥',kind:'action',concept:'변수'},
 REP2:{label:'2번 반복',icon:'×2',kind:'structure',count:2,concept:'반복'},
 REP3:{label:'3번 반복',icon:'×3',kind:'structure',count:3,concept:'반복'},
 REP4:{label:'4번 반복',icon:'×4',kind:'structure',count:4,concept:'반복'},
 IF_ENEMY:{label:'앞에 적이 있다면',icon:'?',kind:'condition',condition:'enemyAhead',concept:'조건'},
 IF_GAP:{label:'앞이 낭떠러지라면',icon:'?',kind:'condition',condition:'gapAhead',concept:'조건'},
 IF_UP:{label:'위에 길이 있다면',icon:'?',kind:'condition',condition:'platformAbove',concept:'조건'},
 IF_HP_LOW:{label:'HP가 2 이하라면',icon:'?',kind:'condition',condition:'hpLow',concept:'변수·조건'},
 IF_WINDUP:{label:'적이 공격 준비 중이면',icon:'!',kind:'condition',condition:'enemyWindup',concept:'상태·조건'},
 IF_CRYSTALS3:{label:'수정이 3개 이상이면',icon:'?',kind:'condition',condition:'crystals3',concept:'변수·조건'},
 CALL_FN:{label:'나의 기술 A',icon:'ƒA',kind:'call',slot:'a',concept:'함수'},
 CALL_FN_B:{label:'나의 기술 B',icon:'ƒB',kind:'call',slot:'b',concept:'함수'},
 UNTIL_GOAL:{label:'목적지까지 반복',icon:'↻',kind:'until',condition:'atGoal',limit:90,concept:'조건 반복'},
 UNTIL_SAFE:{label:'앞이 안전할 때까지',icon:'↻',kind:'until',condition:'safeAhead',limit:30,concept:'조건 반복'},
 UNTIL_ENEMIES_GONE:{label:'적이 모두 사라질 때까지',icon:'↻',kind:'until',condition:'enemiesGone',limit:90,concept:'조건 반복'},
 UNTIL_DATA3:{label:'데이터 3개까지 반복',icon:'↻',kind:'until',condition:'data3',limit:50,concept:'조건 반복'},
 IF_SAFE:{label:'앞이 안전하다면',icon:'?',kind:'condition',condition:'safeAhead',concept:'조건'},
 IF_ITEM:{label:'여기에 수집물이 있다면',icon:'?',kind:'condition',condition:'itemHere',concept:'조건·변수'},
 IF_DOOR:{label:'앞에 문이 있다면',icon:'?',kind:'condition',condition:'doorAhead',concept:'조건'},
 IF_SWITCH:{label:'여기에 스위치가 있다면',icon:'?',kind:'condition',condition:'switchHere',concept:'조건'},
 IF_CONVEYOR:{label:'앞에 컨베이어가 있다면',icon:'?',kind:'condition',condition:'conveyorAhead',concept:'조건'},
 IF_DATA:{label:'여기에 데이터가 있다면',icon:'?',kind:'condition',condition:'dataHere',concept:'조건·변수'},
 IF_DATA3:{label:'데이터가 3개 이상이면',icon:'?',kind:'condition',condition:'data3',concept:'변수·조건'},
 IF_DATA5:{label:'데이터가 5개 이상이면',icon:'?',kind:'condition',condition:'data5',concept:'변수·조건'},
 IF_TERMINAL:{label:'여기에 단말기가 있다면',icon:'?',kind:'condition',condition:'terminalHere',concept:'조건'},
 IF_ENERGY_LOW:{label:'에너지가 4 이하라면',icon:'?',kind:'condition',condition:'energyLow',concept:'변수·조건'},
 IF_CHARGER:{label:'여기에 충전기가 있다면',icon:'?',kind:'condition',condition:'chargerHere',concept:'조건'},
 IF_ENEMY_WINDUP:{label:'적이 있고 공격 준비 중이면',icon:'&&',kind:'condition',condition:'enemyAheadWindup',concept:'논리 AND'},
 TOGGLE:{label:'스위치 전환',icon:'⏻',kind:'action',concept:'상태'},
 COLLECT_DATA:{label:'데이터 수집',icon:'▤',kind:'action',concept:'변수'},
 UPLOAD:{label:'데이터 업로드',icon:'⇧',kind:'action',concept:'변수·상태'},
 CHARGE:{label:'에너지 충전',icon:'⚡',kind:'action',concept:'변수'}
};

function floor(length,gaps=[],y=0){
 const set=new Set(gaps),out=[];let start=null;
 for(let x=0;x<length;x++){
  if(!set.has(x)&&start===null)start=x;
  if((set.has(x)||x===length-1)&&start!==null){
   const end=set.has(x)?x:x+1;
   out.push({x:start,y,w:end-start});
   start=null;
  }
 }
 return out;
}
function P(x,y,w){return {x,y,w};}
const PRO=['FWD','JUMP','ATTACK','COLLECT','OPEN','REP2','REP3','REP4','IF_ENEMY','IF_GAP','IF_CRYSTALS3','CALL_FN'];

const M=[
 {arc:'prologue',chapter:'입단 시험 · 1',concept:'순차 실행',title:'첫 발걸음',name:'1. 오른쪽으로 출발!',text:'코드는 위에서 아래로 실행돼요. 앞으로 달리기를 이어 붙여 출구까지 가 보세요.',objective:'출구까지 달려가기',start:{x:1,y:0},goal:{x:5,y:0},platforms:floor(8),crystals:[],doors:[],enemies:[],treasures:[],memory:7,par:4,available:['FWD'],reward:{id:'boots_basic',name:'원정대 장화',desc:'앞으로 달리기 명령을 익혔어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 2',concept:'점프와 순서',title:'길이 끊겼어',name:'2. 점프!',text:'앞이 끊겼다면 점프가 필요해요. 실행 순서를 바르게 배치해 구덩이를 건너세요.',objective:'구덩이를 뛰어넘어 출구로',start:{x:1,y:0},goal:{x:8,y:0},platforms:floor(10,[4]),crystals:[],doors:[],enemies:[],treasures:[],memory:9,par:7,available:['FWD','JUMP'],reward:{id:'jump_module',name:'점프 모듈',desc:'점프로 끊어진 길을 건널 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 3',concept:'순차 실행',title:'수정과 문',name:'3. 먼저 줍고, 그다음 열기',text:'수정을 지나치지 말고 그 자리에서 주운 뒤 문을 여세요.',objective:'수정 1개를 챙겨 문을 열고 출구로',start:{x:1,y:0},goal:{x:8,y:0},platforms:floor(10),crystals:[{x:3,y:0}],doors:[{x:6,y:0,need:1}],enemies:[],treasures:[],memory:10,par:9,available:['FWD','COLLECT','OPEN'],reward:{id:'hand_module',name:'수집 모듈',desc:'필드의 수정과 보물을 주울 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 4',concept:'행동과 디버깅',title:'첫 버그 몬스터',name:'4. 가까이 가서 공격!',text:'적이 바로 앞에 있을 때만 공격이 성공해요. 잘못된 줄에서 프로그램이 멈춥니다.',objective:'버그 몬스터를 쓰러뜨리고 출구로',start:{x:1,y:0},goal:{x:9,y:0},platforms:floor(11),crystals:[],doors:[],enemies:[{x:5,y:0,type:'blob',hp:1}],treasures:[],memory:11,par:9,available:['FWD','ATTACK'],reward:{id:'sword_module',name:'디버그 블레이드',desc:'버그 몬스터를 공격할 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 5',concept:'반복문',title:'같은 행동이 계속돼',name:'5. 반복해서 돌파!',text:'같은 코드를 길게 복사하지 말고 반복 블록 안에 묶어 보세요.',objective:'버그 몬스터 3마리를 지나 출구로',start:{x:1,y:0},goal:{x:13,y:0},platforms:floor(15),crystals:[],doors:[],enemies:[{x:4,y:0,type:'mush',hp:1},{x:8,y:0,type:'mush',hp:1},{x:12,y:0,type:'mush',hp:1}],treasures:[],memory:8,par:6,available:['FWD','ATTACK','REP2','REP3','REP4'],reward:{id:'loop_core',name:'반복 코어',desc:'같은 행동 묶음을 여러 번 실행할 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 6',concept:'조건문',title:'있을 때만 공격',name:'6. 적을 보고 판단해',text:'몬스터 위치가 달라져도 작동하는 코드를 만들어 보세요.',objective:'적 감지 조건을 사용해 어떤 배치에서도 통과',start:{x:1,y:0},goal:{x:10,y:0},platforms:floor(12),crystals:[],doors:[],enemies:[{x:4,y:0,type:'blob',hp:1},{x:8,y:0,type:'blob',hp:1}],variants:[[4,8],[3,8],[5,7]],validationTests:[{id:'enemy_shift_a',name:'적 위치 변경 A',enemies:[3,8]},{id:'enemy_shift_b',name:'적 위치 변경 B',enemies:[5,7]}],treasures:[],memory:9,par:8,available:['FWD','ATTACK','REP4','IF_ENEMY'],requireType:'IF_ENEMY',requireConditionCoverage:'IF_ENEMY',reward:{id:'enemy_sensor',name:'적 감지 센서',desc:'앞에 적이 있는지 조건으로 확인할 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 7',concept:'조건문',title:'길을 읽고 달리기',name:'7. 떨어지기 전에 점프!',text:'구덩이 위치를 외우지 말고 센서로 판단하세요.',objective:'낭떠러지 조건을 사용해 출구로',start:{x:1,y:0},goal:{x:12,y:0},platforms:floor(14,[5,9]),validationTests:[{id:'gap_shift_a',name:'절벽 위치 변경 A',platforms:floor(14,[4,8])},{id:'gap_shift_b',name:'절벽 위치 변경 B',platforms:floor(14,[3,7])}],crystals:[],doors:[],enemies:[],treasures:[],memory:9,par:7,available:['FWD','JUMP','REP4','IF_GAP'],requireType:'IF_GAP',requireConditionCoverage:'IF_GAP',reward:{id:'terrain_sensor',name:'지형 센서',desc:'앞의 낭떠러지를 코드로 감지할 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 8',concept:'변수와 조건',title:'수정 = ?',name:'8. 세 개를 모으면 열려',text:'수정을 주울 때마다 수정 값이 1씩 올라가요. 3개가 되었을 때 문을 여세요.',objective:'수정 3개를 모아 문을 열고 출구로',start:{x:1,y:0},goal:{x:11,y:0},platforms:floor(13),crystals:[{x:3,y:0},{x:5,y:0},{x:7,y:0}],doors:[{x:9,y:0,need:3}],enemies:[],treasures:[],memory:12,par:10,available:['FWD','COLLECT','OPEN','REP3','IF_CRYSTALS3'],requireType:'IF_CRYSTALS3',requireConditionTrue:'IF_CRYSTALS3',reward:{id:'memory_sensor',name:'상태 메모리',desc:'수정 개수 같은 값을 조건으로 읽을 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 9',concept:'함수',title:'내 기술 만들기',name:'9. 자주 쓰는 행동을 묶자',text:'자주 쓰는 전투 행동을 나의 기술에 저장하고 메인 코드에서 불러오세요.',objective:'나의 기술을 사용해 3마리 돌파',start:{x:1,y:0},goal:{x:13,y:0},platforms:floor(15),crystals:[],doors:[],enemies:[{x:4,y:0,type:'ghost',hp:1},{x:8,y:0,type:'ghost',hp:1},{x:12,y:0,type:'ghost',hp:1}],treasures:[],memory:8,par:5,totalPar:8,functionMemory:7,available:['FWD','ATTACK','REP3','IF_ENEMY','CALL_FN'],requireType:'CALL_FN',requireFunction:true,requireCallCount:2,reward:{id:'function_slot',name:'기술 슬롯',desc:'자주 쓰는 코드를 나의 기술로 저장할 수 있어요.'}},
 {arc:'prologue',chapter:'입단 시험 · 최종',concept:'종합',title:'NULL 골렘',name:'10. 입단 시험 최종전',text:'달리고, 줍고, 판단하고, 싸우세요. 지금까지 익힌 코드를 모두 사용하는 마지막 시험입니다.',objective:'수정 3개 → 문 열기 → 골렘 격파 → 출구',start:{x:1,y:0},goal:{x:16,y:0},platforms:floor(18,[6]),crystals:[{x:2,y:0},{x:3,y:0},{x:4,y:0}],doors:[{x:10,y:0,need:3}],enemies:[{x:14,y:0,type:'golem',hp:3,cycle:['idle','windup','slam','rest']}],treasures:[],memory:20,par:15,functionMemory:8,available:PRO,requireType:'IF_CRYSTALS3',reward:{id:'ranger_badge',name:'코드 원정대 배지',desc:'입단 시험 통과! 이제 버그월드 본편으로 출발할 수 있어요.',worldUnlock:'forest'}},

 {arc:'forest',chapter:'버섯 숲 · 1',concept:'분기와 탐험',title:'두 갈래 숲길',name:'11. 어느 길로 갈까?',text:'본편에서는 길이 위아래로 갈라져요. 위쪽은 짧고 보물이 있지만 점프가 더 필요합니다.',objective:'원하는 경로를 골라 숲 관문까지 이동',start:{x:1,y:0},goal:{x:17,y:0},platforms:[P(0,0,7),P(8,0,5),P(14,0,5),P(5,2,6),P(11,1,4),P(6,-2,8)],crystals:[],doors:[],enemies:[{x:9,y:0,type:'blob',hp:1},{x:8,y:2,type:'mush',hp:1}],checkpoints:[{x:10,name:'숲속 쉼터'}],treasures:[{x:7,y:2,id:'forest_cache',name:'숲의 메모리 조각'}],memory:16,par:12,functionMemory:8,available:['FWD','BACK','JUMP','ATTACK','COLLECT','REP2','REP3','REP4','IF_ENEMY','IF_GAP','CALL_FN'],carryProgram:true,reward:{id:'reflex_sensor',name:'반응 센서',desc:'적이 공격 준비 중인지 읽을 수 있어요.',unlockBlocks:['IF_WINDUP','DODGE','WAIT']}},
 {arc:'forest',chapter:'버섯 숲 · 2',concept:'상태 감지',title:'독포자 사수',name:'12. 공격 예고를 읽어!',text:'독버섯은 포자를 쏘기 전에 몸이 붉게 빛나요. 공격 준비 상태를 읽고 회피하세요.',objective:'독포자 공격을 피하며 숲을 통과',start:{x:1,y:0},goal:{x:15,y:0},platforms:[P(0,0,17),P(7,2,4)],crystals:[],doors:[],enemies:[{x:6,y:0,type:'spitter',hp:2,cycle:['idle','windup','shoot','rest']},{x:12,y:0,type:'spitter',hp:2,cycle:['idle','windup','shoot','rest']}],checkpoints:[{x:9,name:'포자 샘터'}],validationTests:[{id:'spore_timing_a',name:'포자 타이밍 변경 A',enemies:[{x:6,y:0,type:'spitter',hp:2,cycle:['idle','windup','shoot','rest'],initialStateIndex:1},{x:12,y:0,type:'spitter',hp:2,cycle:['idle','windup','shoot','rest'],initialStateIndex:3}]}],treasures:[{x:9,y:2,id:'altimeter_chip',name:'고도 측정 칩'}],memory:18,par:13,functionMemory:9,available:['FWD','BACK','JUMP','DODGE','ATTACK','WAIT','COLLECT','REP2','REP3','REP4','IF_ENEMY','IF_GAP','IF_WINDUP','CALL_FN'],requireType:'IF_WINDUP',requireConditionTrue:'IF_WINDUP',carryProgram:true,reward:{id:'altimeter',name:'고도 센서',desc:'위쪽에 올라갈 수 있는 길이 있는지 감지할 수 있어요.',unlockBlocks:['IF_UP']}},
 {arc:'forest',chapter:'버섯 숲 · 3',concept:'높이와 경로',title:'박쥐 절벽',name:'13. 위쪽 길을 노려라',text:'이번에는 위쪽 발판에 희귀 보물이 있어요. 고도 센서로 올라갈 기회를 찾아 보세요.',objective:'절벽을 넘어 숲 깊숙이 이동',start:{x:1,y:0},goal:{x:17,y:0},platforms:[P(0,0,5),P(6,0,5),P(12,0,7),P(4,2,4),P(8,4,5),P(13,2,4),P(5,-2,5)],crystals:[],doors:[],enemies:[{x:7,y:2,type:'bat',hp:1,cycle:['hover','windup','swoop','rest']},{x:11,y:4,type:'bat',hp:1,cycle:['hover','windup','swoop','rest']}],checkpoints:[{x:12,name:'절벽 전망대'}],treasures:[{x:10,y:4,id:'sky_shard',name:'하늘빛 수정'}],memory:19,par:14,functionMemory:9,available:['FWD','BACK','JUMP','DODGE','ATTACK','WAIT','COLLECT','REP2','REP3','REP4','IF_ENEMY','IF_GAP','IF_WINDUP','IF_UP','CALL_FN'],carryProgram:true,reward:{id:'high_jump_boots',name:'고점프 부츠',desc:'더 높은 발판으로 뛰어오르거나 아래 길로 내려갈 수 있어요.',unlockBlocks:['HIGH_JUMP','DROP']}},
 {arc:'forest',chapter:'버섯 숲 · 4',concept:'빌드와 보상',title:'숨은 보물길',name:'14. 위험한 길, 좋은 보상',text:'안전한 아래 길과 위험한 위 길 중 하나를 고르세요. 위 길에는 메모리 코어가 숨겨져 있습니다.',objective:'경로를 선택해 왕버섯 둥지 앞까지 이동',start:{x:1,y:0},goal:{x:19,y:0},platforms:[P(0,0,6),P(7,0,6),P(14,0,7),P(5,3,5),P(10,5,5),P(15,3,4),P(6,-2,8)],crystals:[],doors:[],enemies:[{x:8,y:0,type:'shield',hp:2,cycle:['guard','open','guard','open']},{x:12,y:5,type:'spitter',hp:2,cycle:['idle','windup','shoot','rest']},{x:16,y:3,type:'bat',hp:1,cycle:['hover','windup','swoop','rest']}],checkpoints:[{x:14,name:'왕버섯 둥지 입구'}],treasures:[{x:13,y:5,id:'memory_core',name:'메모리 코어 +2',memoryBonus:2}],memory:21,par:16,functionMemory:10,available:['FWD','BACK','JUMP','HIGH_JUMP','DROP','DODGE','ATTACK','WAIT','COLLECT','REP2','REP3','REP4','IF_ENEMY','IF_GAP','IF_WINDUP','IF_UP','CALL_FN'],carryProgram:true,reward:{id:'dash_boots',name:'대시 부츠',desc:'두 칸을 빠르게 돌파하는 대시 명령을 사용할 수 있어요.',unlockBlocks:['DASH']}},
 {arc:'forest',chapter:'버섯 숲 · 보스',concept:'상태·회피·공격',title:'왕버섯 BUGCAP',name:'15. 버섯 숲의 주인',text:'왕버섯은 독포자를 뿜기 전 공격 준비 상태가 됩니다. 회피와 공격 타이밍을 프로그램하세요.',objective:'BUGCAP을 쓰러뜨리고 숲의 코어 회수',start:{x:1,y:0},goal:{x:18,y:0},platforms:[P(0,0,20),P(6,2,4),P(12,2,4)],crystals:[],doors:[],enemies:[{x:14,y:0,type:'boss_mushroom',hp:8,boss:true,cycle:['idle','windup','spore','rest','rest']}],checkpoints:[{x:10,name:'보스 전초지'}],validationTests:[{id:'bugcap_timing_a',name:'BUGCAP 패턴 변경',enemies:[{x:14,y:0,type:'boss_mushroom',hp:8,boss:true,cycle:['idle','windup','spore','rest','rest'],initialStateIndex:3}]}],treasures:[{x:17,y:0,id:'forest_core',name:'버섯 숲 코어'}],memory:24,par:18,functionMemory:11,available:['FWD','BACK','JUMP','HIGH_JUMP','DROP','DASH','DODGE','ATTACK','WAIT','COLLECT','HEAL','REP2','REP3','REP4','IF_ENEMY','IF_GAP','IF_WINDUP','IF_HP_LOW','IF_UP','CALL_FN'],requireType:'IF_WINDUP',requireConditionTrue:'IF_WINDUP',carryProgram:true,boss:true,reward:{id:'forest_core',name:'버섯 숲 코어',desc:'버섯 숲의 버그를 정화했어요. 조건 반복 코어가 열립니다.',memoryBonus:4,unlockBlocks:['UNTIL_GOAL']}},

 // 수정 광산 · 16~20
 {arc:'mine',chapter:'수정 광산 · 1',concept:'조건 반복',title:'무너지는 터널',name:'16. 끝이 보일 때까지',text:'터널의 균열 위치가 매번 달라져요. 칸 수를 외우지 말고 목적지에 도착할 때까지 주변을 읽으며 움직이세요.',objective:'목적지까지 반복을 사용해 변형 터널 3개 통과',start:{x:1,y:0},goal:{x:16,y:0},platforms:floor(18,[5,10,14]),crystals:[],doors:[],enemies:[],treasures:[],memory:10,par:5,available:['FWD','JUMP','IF_GAP','UNTIL_GOAL'],requireType:'UNTIL_GOAL',validationTests:[{id:'mine_gap_a',name:'터널 균열 A',platforms:floor(18,[4,9,13])},{id:'mine_gap_b',name:'터널 균열 B',platforms:floor(18,[6,11,14])}],reward:{id:'auto_loop_core',name:'자동 반복 코어',desc:'조건이 만족될 때까지 반복하는 명령을 사용할 수 있어요.',unlockBlocks:['UNTIL_SAFE']}},
 {arc:'mine',chapter:'수정 광산 · 2',concept:'상태 대기',title:'광차 통행로',name:'17. 지나갈 때까지 기다려',text:'폭주 광차는 위험 신호와 안전 신호를 반복해요. 안전해질 때까지 기다린 뒤 전진하세요.',objective:'광차 타이밍이 달라도 안전하게 출구로',start:{x:1,y:0},goal:{x:14,y:0},platforms:floor(16),crystals:[],doors:[],hazards:[{x:5,type:'cart',cycle:['safe','danger','danger','safe']},{x:10,type:'cart',cycle:['danger','safe','danger','safe']}],enemies:[],treasures:[],memory:11,par:7,available:['FWD','WAIT','UNTIL_GOAL','UNTIL_SAFE','IF_SAFE'],requireType:'UNTIL_SAFE',validationTests:[{id:'cart_phase',name:'광차 출발 시점 변경',hazards:[{x:5,type:'cart',cycle:['safe','danger','danger','safe'],initialStateIndex:2},{x:10,type:'cart',cycle:['danger','safe','danger','safe'],initialStateIndex:1}]}],reward:{id:'proximity_sensor',name:'통행 센서',desc:'위험 구간이 안전한지 읽을 수 있어요.',unlockBlocks:['IF_SAFE']}},
 {arc:'mine',chapter:'수정 광산 · 3',concept:'카운터·탐색',title:'흩어진 광석',name:'18. 다섯 개를 찾아라',text:'수정 위치가 달라져도 수집물이 있는 곳을 감지하고 5개를 모두 모아 봉인문을 여세요.',objective:'수정 5개를 모아 문을 열고 출구로',start:{x:1,y:0},goal:{x:17,y:0},platforms:floor(19),crystals:[{x:3,y:0},{x:5,y:0},{x:8,y:0},{x:11,y:0},{x:13,y:0}],doors:[{x:15,y:0,need:5}],enemies:[],treasures:[],memory:14,par:9,available:['FWD','COLLECT','OPEN','UNTIL_GOAL','IF_ITEM','IF_DOOR'],requireType:'IF_ITEM',validationTests:[{id:'ore_shift',name:'광석 위치 변경',crystals:[{x:2,y:0},{x:6,y:0},{x:9,y:0},{x:12,y:0},{x:14,y:0}]}],reward:{id:'ore_scanner',name:'광석 스캐너',desc:'현재 위치의 수집물과 앞의 문을 감지합니다.',unlockBlocks:['IF_ITEM','IF_DOOR']}},
 {arc:'mine',chapter:'수정 광산 · 4',concept:'논리 AND',title:'경비 로봇',name:'19. 두 조건을 함께 봐',text:'경비 로봇이 바로 앞에 있고 동시에 공격 준비 중일 때만 회피하면 돼요. 중첩 조건으로 두 상태를 함께 판단해 보세요.',objective:'중첩 조건으로 로봇 2대를 안전하게 돌파',start:{x:1,y:0},goal:{x:15,y:0},platforms:floor(17),crystals:[],doors:[],enemies:[{x:6,y:0,type:'golem',hp:2,cycle:['idle','windup','slam','rest']},{x:11,y:0,type:'golem',hp:2,cycle:['rest','idle','windup','slam']}],treasures:[],memory:16,par:11,available:['FWD','ATTACK','DODGE','WAIT','IF_ENEMY','IF_WINDUP','UNTIL_GOAL'],requireTypes:['IF_ENEMY','IF_WINDUP'],reward:{id:'logic_core',name:'논리 결합 코어',desc:'두 조건을 한 번에 읽는 AND 센서가 열립니다.',unlockBlocks:['IF_ENEMY_WINDUP']}},
 {arc:'mine',chapter:'수정 광산 · 보스',concept:'상태 기반 AI',title:'감독관 ORE-0',name:'20. 광산 감독관',text:'ORE-0의 공격 순서는 매번 달라져요. 공격 준비 신호를 읽고 피한 뒤 빈틈에 공격하세요.',objective:'ORE-0 격파 후 광산 코어 회수',start:{x:1,y:0},goal:{x:17,y:0},platforms:floor(19),crystals:[],doors:[],enemies:[{x:13,y:0,type:'mine_overseer',hp:9,boss:true,cycle:['idle','windup','slam','rest','guard','rest']}],treasures:[{x:16,y:0,id:'mine_core',name:'수정 광산 코어'}],memory:20,par:12,available:['FWD','ATTACK','DODGE','WAIT','IF_ENEMY','IF_WINDUP','IF_ENEMY_WINDUP','UNTIL_GOAL','UNTIL_ENEMIES_GONE'],requireType:'IF_ENEMY_WINDUP',validationTests:[{id:'ore0_phase',name:'ORE-0 패턴 변경',enemies:[{x:13,y:0,type:'mine_overseer',hp:9,boss:true,cycle:['guard','rest','idle','windup','slam','rest'],initialStateIndex:2}]}],boss:true,reward:{id:'mine_core',name:'수정 광산 코어',desc:'두 번째 기술 슬롯이 해금됩니다.',memoryBonus:3,unlockBlocks:['CALL_FN_B','UNTIL_ENEMIES_GONE']}},

 // 기계 도시 · 21~25
 {arc:'city',chapter:'기계 도시 · 1',concept:'다중 함수',title:'두 개의 기술',name:'21. 이동과 전투를 나눠라',text:'이제 나의 기술 A와 B를 따로 만들 수 있어요. 하나는 이동, 하나는 전투처럼 역할을 나누어 재사용하세요.',objective:'기술 A와 B를 모두 호출해 출구로',start:{x:1,y:0},goal:{x:15,y:0},platforms:floor(17,[8]),crystals:[],doors:[],enemies:[{x:5,y:0,type:'robot',hp:1},{x:12,y:0,type:'robot',hp:1}],treasures:[],memory:11,functionMemory:8,par:8,totalPar:16,available:['FWD','JUMP','ATTACK','IF_ENEMY','IF_GAP','REP2','REP3','CALL_FN','CALL_FN_B'],requireFunction:true,requireFunctionB:true,requireTypes:['CALL_FN','CALL_FN_B'],reward:{id:'dual_function_core',name:'듀얼 기술 코어',desc:'기술 A/B를 독립적으로 저장하고 호출할 수 있어요.'}},
 {arc:'city',chapter:'기계 도시 · 2',concept:'상태 전환',title:'전력 스위치',name:'22. 스위치를 켜!',text:'도시 문은 연결된 스위치를 켜야 열립니다. 스위치 위치가 바뀌어도 감지해서 작동시키세요.',objective:'스위치 2개를 켜고 출구로',start:{x:1,y:0},goal:{x:16,y:0},platforms:floor(18),switches:[{id:'a',x:4,y:0},{id:'b',x:10,y:0}],doors:[{x:6,y:0,switchId:'a'},{x:12,y:0,switchId:'b'}],crystals:[],enemies:[],treasures:[],memory:13,par:8,available:['FWD','TOGGLE','IF_SWITCH','IF_DOOR','UNTIL_GOAL'],requireType:'TOGGLE',validationTests:[{id:'switch_shift',name:'스위치 위치 변경',switches:[{id:'a',x:3,y:0},{id:'b',x:9,y:0}],doors:[{x:5,y:0,switchId:'a'},{x:11,y:0,switchId:'b'}]}],reward:{id:'switch_tool',name:'스위치 툴',desc:'현장의 스위치 상태를 바꿀 수 있어요.',unlockBlocks:['TOGGLE','IF_SWITCH']}},
 {arc:'city',chapter:'기계 도시 · 3',concept:'자동 이동·보정',title:'역주행 컨베이어',name:'23. 밀려나도 다시 계산해',text:'컨베이어가 행동 뒤 캐릭터를 한 칸 밀 수 있어요. 위치를 외우지 말고 센서와 반복으로 경로를 보정하세요.',objective:'컨베이어 구간을 지나 출구로',start:{x:1,y:0},goal:{x:16,y:0},platforms:floor(18,[9]),conveyors:[{from:4,to:7,dir:-1},{from:11,to:14,dir:1}],crystals:[],doors:[],enemies:[],treasures:[],memory:14,par:8,available:['FWD','JUMP','IF_GAP','IF_CONVEYOR','UNTIL_GOAL'],requireType:'IF_CONVEYOR',reward:{id:'motion_compass',name:'동작 보정기',desc:'자동 이동이 있는 지형에서도 반복 로직을 안정화합니다.'}},
 {arc:'city',chapter:'기계 도시 · 4',concept:'위험 상태',title:'레이저 회랑',name:'24. 신호를 읽고 건너',text:'레이저는 켜짐과 꺼짐을 반복합니다. 안전 신호를 읽고 기다렸다가 통과하세요.',objective:'레이저 3개를 안전하게 통과',start:{x:1,y:0},goal:{x:15,y:0},platforms:floor(17),hazards:[{x:4,type:'laser',cycle:['safe','danger']},{x:8,type:'laser',cycle:['danger','safe','danger']},{x:12,type:'laser',cycle:['safe','danger','danger','safe']}],crystals:[],doors:[],enemies:[],treasures:[],memory:13,par:8,available:['FWD','WAIT','UNTIL_SAFE','UNTIL_GOAL','IF_SAFE'],requireType:'UNTIL_SAFE',validationTests:[{id:'laser_phase',name:'레이저 위상 변경',hazards:[{x:4,type:'laser',cycle:['danger','safe'],initialStateIndex:1},{x:8,type:'laser',cycle:['safe','danger','safe'],initialStateIndex:2},{x:12,type:'laser',cycle:['danger','danger','safe','safe'],initialStateIndex:1}]}],reward:{id:'laser_sensor',name:'레이저 센서',desc:'주기적으로 바뀌는 위험 상태를 읽습니다.'}},
 {arc:'city',chapter:'기계 도시 · 보스',concept:'함수·상태·스위치',title:'중앙 AI GEAR',name:'25. 도시를 다시 켜라',text:'중앙 AI가 문과 방어 로봇을 동시에 통제합니다. 두 기술과 스위치를 조합해 코어에 접근하세요.',objective:'스위치 가동 → 로봇 격파 → GEAR 코어 정지',start:{x:1,y:0},goal:{x:19,y:0},platforms:floor(21,[9]),switches:[{id:'gate',x:5,y:0}],doors:[{x:7,y:0,switchId:'gate'}],enemies:[{x:12,y:0,type:'robot',hp:2},{x:16,y:0,type:'gear_boss',hp:10,boss:true,cycle:['guard','windup','slam','rest','rest']}],crystals:[],treasures:[{x:18,y:0,id:'city_core',name:'기계 도시 코어'}],memory:22,functionMemory:10,par:14,totalPar:22,available:['FWD','JUMP','ATTACK','DODGE','WAIT','HEAL','TOGGLE','IF_HP_LOW','IF_SWITCH','IF_ENEMY','IF_WINDUP','IF_GAP','UNTIL_GOAL','CALL_FN','CALL_FN_B'],requireFunctionB:true,requireTypes:['CALL_FN','CALL_FN_B','TOGGLE'],boss:true,reward:{id:'city_core',name:'기계 도시 코어',desc:'데이터 수집과 업로드 기능이 해금됩니다.',memoryBonus:3,unlockBlocks:['COLLECT_DATA','IF_DATA','IF_DATA3','IF_DATA5','UPLOAD','IF_TERMINAL']}},

 // 데이터 사막 · 26~30
 {arc:'desert',chapter:'데이터 사막 · 1',concept:'새 변수',title:'흩어진 패킷',name:'26. 데이터 = ?',text:'데이터 조각은 수정과 별개의 변수예요. 위치가 달라져도 감지하고 3개를 모으세요.',objective:'데이터 3개를 모아 출구로',start:{x:1,y:0},goal:{x:14,y:0},platforms:floor(16),dataItems:[{x:3,y:0},{x:6,y:0},{x:10,y:0}],crystals:[],doors:[],enemies:[],treasures:[],memory:12,par:7,available:['FWD','COLLECT_DATA','IF_DATA','UNTIL_GOAL','IF_DATA3'],requireType:'COLLECT_DATA',validationTests:[{id:'data_shift',name:'패킷 위치 변경',dataItems:[{x:2,y:0},{x:7,y:0},{x:11,y:0}]}],reward:{id:'data_scanner',name:'데이터 스캐너',desc:'현재 위치의 데이터 패킷을 감지합니다.'}},
 {arc:'desert',chapter:'데이터 사막 · 2',concept:'업로드·상태',title:'중계 단말기',name:'27. 모은 값을 사용해',text:'데이터를 모으는 것만으로는 부족해요. 단말기에 도착하면 필요한 개수를 확인해 업로드하세요.',objective:'데이터 3개를 모아 단말기에 업로드',start:{x:1,y:0},goal:{x:15,y:0},platforms:floor(17),dataItems:[{x:3,y:0},{x:5,y:0},{x:8,y:0}],terminals:[{id:'t1',x:10,y:0,need:3}],doors:[{x:12,y:0,terminalId:'t1'}],crystals:[],enemies:[],treasures:[],memory:14,par:9,available:['FWD','COLLECT_DATA','UPLOAD','IF_DATA','IF_TERMINAL','UNTIL_GOAL'],requireUploads:1,requireType:'UPLOAD',reward:{id:'upload_module',name:'업로드 모듈',desc:'데이터를 단말기에 전달해 시스템 상태를 바꿉니다.'}},
 {arc:'desert',chapter:'데이터 사막 · 3',concept:'자원 관리',title:'전력이 부족해',name:'28. 에너지를 관리해',text:'이 구역에서는 이동할 때 에너지가 줄어요. 에너지가 낮아지면 충전기를 찾아 충전해야 합니다.',objective:'에너지를 고갈시키지 않고 출구로',start:{x:1,y:0},goal:{x:16,y:0},platforms:floor(18),usesEnergy:true,startEnergy:6,rechargeStations:[{x:6,y:0},{x:12,y:0}],crystals:[],doors:[],enemies:[],treasures:[],memory:14,par:9,available:['FWD','CHARGE','IF_ENERGY_LOW','IF_CHARGER','UNTIL_GOAL'],requireType:'CHARGE',reward:{id:'energy_cell',name:'에너지 셀',desc:'에너지 상태와 충전기를 사용할 수 있어요.',unlockBlocks:['CHARGE','IF_ENERGY_LOW','IF_CHARGER']}},
 {arc:'desert',chapter:'데이터 사막 · 4',concept:'복수 변수',title:'패킷과 전력',name:'29. 두 값을 동시에 관리해',text:'데이터를 모으면서 에너지까지 관리해야 해요. 서로 다른 두 변수를 읽고 행동을 바꿔 보세요.',objective:'데이터 5개 수집·업로드 후 출구로',start:{x:1,y:0},goal:{x:19,y:0},platforms:floor(21,[10]),usesEnergy:true,startEnergy:8,rechargeStations:[{x:7,y:0},{x:15,y:0}],dataItems:[{x:3,y:0},{x:5,y:0},{x:9,y:0},{x:13,y:0},{x:16,y:0}],terminals:[{id:'t1',x:17,y:0,need:5}],doors:[{x:18,y:0,terminalId:'t1'}],crystals:[],enemies:[],treasures:[],memory:19,par:12,available:['FWD','JUMP','CHARGE','COLLECT_DATA','UPLOAD','IF_GAP','IF_DATA','IF_TERMINAL','IF_ENERGY_LOW','IF_CHARGER','UNTIL_GOAL'],requireUploads:1,requireTypes:['COLLECT_DATA','CHARGE','UPLOAD'],validationTests:[{id:'desert_mix',name:'자원 배치 변경',dataItems:[{x:2,y:0},{x:6,y:0},{x:9,y:0},{x:12,y:0},{x:16,y:0}],rechargeStations:[{x:5,y:0},{x:12,y:0}]}],reward:{id:'resource_core',name:'자원 판단 코어',desc:'여러 상태 변수를 함께 관리하는 원정 장비입니다.'}},
 {arc:'desert',chapter:'데이터 사막 · 보스',concept:'변수·전투 종합',title:'MIRAGE 서버',name:'30. 가짜 신호를 넘어',text:'MIRAGE는 공격과 데이터 교란을 번갈아 사용합니다. 에너지, 데이터, 적 상태를 모두 읽어 코어를 정지하세요.',objective:'데이터 3개 업로드 후 MIRAGE 격파',start:{x:1,y:0},goal:{x:20,y:0},platforms:floor(22),usesEnergy:true,startEnergy:10,rechargeStations:[{x:7,y:0},{x:16,y:0}],dataItems:[{x:3,y:0},{x:9,y:0},{x:13,y:0}],terminals:[{id:'seal',x:16,y:0,need:3}],doors:[{x:17,y:0,terminalId:'seal'}],enemies:[{x:18,y:0,type:'mirage_boss',hp:10,boss:true,cycle:['idle','windup','shoot','rest','guard','rest']}],crystals:[],treasures:[{x:19,y:0,id:'desert_core',name:'데이터 사막 코어'}],memory:24,functionMemory:11,par:16,totalPar:25,available:['FWD','ATTACK','DODGE','WAIT','HEAL','CHARGE','COLLECT_DATA','UPLOAD','IF_HP_LOW','IF_ENEMY','IF_WINDUP','IF_DATA','IF_TERMINAL','IF_ENERGY_LOW','IF_CHARGER','UNTIL_GOAL','CALL_FN','CALL_FN_B'],requireUploads:1,requireType:'UPLOAD',boss:true,reward:{id:'desert_core',name:'데이터 사막 코어',desc:'성채의 종합 검증 모드가 열립니다.',memoryBonus:4}},

 // 버그 성채 · 31~35
 {arc:'citadel',chapter:'버그 성채 · 1',concept:'종합 일반화',title:'첫 번째 방화벽',name:'31. 한 코드로 모두 대응해',text:'적, 절벽, 레이저 배치가 검증마다 달라집니다. 현재 맵만 통과하는 코드는 성채에서 살아남지 못해요.',objective:'세 가지 변형 성채를 같은 코드로 통과',start:{x:1,y:0},goal:{x:17,y:0},platforms:floor(19,[8]),hazards:[{x:5,type:'laser',cycle:['safe','danger']}],enemies:[{x:11,y:0,type:'robot',hp:1}],crystals:[],doors:[],treasures:[],memory:17,par:10,available:['FWD','JUMP','ATTACK','WAIT','IF_GAP','IF_ENEMY','UNTIL_SAFE','UNTIL_GOAL'],validationTests:[{id:'citadel_a',name:'성채 변형 A',platforms:floor(19,[6]),hazards:[{x:9,type:'laser',cycle:['danger','safe']}],enemies:[{x:13,y:0,type:'robot',hp:1}]},{id:'citadel_b',name:'성채 변형 B',platforms:floor(19,[10]),hazards:[{x:4,type:'laser',cycle:['safe','danger','danger']}],enemies:[{x:8,y:0,type:'robot',hp:1}]}],reward:{id:'citadel_key',name:'성채 접근 키',desc:'복합 검증 임무에 접근할 수 있어요.'}},
 {arc:'citadel',chapter:'버그 성채 · 2',concept:'다중 함수 종합',title:'재사용 시험',name:'32. 기술을 조합해',text:'전투와 이동을 각각 기술로 만들고 여러 상황에서 반복 호출하세요.',objective:'기술 A/B를 각각 2회 이상 사용해 통과',start:{x:1,y:0},goal:{x:18,y:0},platforms:floor(20,[7,14]),enemies:[{x:5,y:0,type:'robot',hp:1},{x:12,y:0,type:'robot',hp:1}],crystals:[],doors:[],treasures:[],memory:12,functionMemory:9,par:8,totalPar:20,available:['FWD','JUMP','ATTACK','IF_ENEMY','IF_GAP','CALL_FN','CALL_FN_B','REP2','REP3'],requireFunction:true,requireFunctionB:true,requireCallSlots:{a:2,b:2},reward:{id:'reuse_badge',name:'재사용 배지',desc:'두 기술을 역할별로 나누어 재사용했습니다.'}},
 {arc:'citadel',chapter:'버그 성채 · 3',concept:'시스템 상태',title:'세 개의 제어실',name:'33. 상태를 바꾸며 전진해',text:'스위치, 데이터 단말기, 레이저를 한 구역에서 모두 처리하세요.',objective:'스위치 가동·데이터 업로드·레이저 통과',start:{x:1,y:0},goal:{x:20,y:0},platforms:floor(22),switches:[{id:'a',x:4,y:0}],doors:[{x:6,y:0,switchId:'a'},{x:16,y:0,terminalId:'t'}],dataItems:[{x:8,y:0},{x:10,y:0},{x:12,y:0}],terminals:[{id:'t',x:14,y:0,need:3}],hazards:[{x:18,type:'laser',cycle:['danger','safe']}],crystals:[],enemies:[],treasures:[],memory:20,par:13,available:['FWD','WAIT','TOGGLE','COLLECT_DATA','UPLOAD','IF_SWITCH','IF_DATA','IF_TERMINAL','UNTIL_SAFE','UNTIL_GOAL'],requireTypes:['TOGGLE','UPLOAD'],reward:{id:'system_core',name:'시스템 코어',desc:'서로 다른 상태 장치를 하나의 프로그램으로 제어합니다.'}},
 {arc:'citadel',chapter:'버그 성채 · 4',concept:'회복·자원·전투',title:'고장난 복도',name:'34. 살아남는 코드',text:'전투 피해와 에너지 소모를 동시에 관리해야 합니다. HP와 에너지가 낮을 때 행동을 바꾸세요.',objective:'HP와 에너지를 관리하며 출구로',start:{x:1,y:0},goal:{x:20,y:0},platforms:floor(22),usesEnergy:true,startEnergy:9,rechargeStations:[{x:7,y:0},{x:15,y:0}],enemies:[{x:5,y:0,type:'golem',hp:2},{x:12,y:0,type:'spitter',hp:2,cycle:['idle','windup','shoot','rest']},{x:18,y:0,type:'robot',hp:1}],crystals:[],doors:[],treasures:[],memory:22,par:15,available:['FWD','ATTACK','DODGE','WAIT','HEAL','CHARGE','IF_HP_LOW','IF_ENERGY_LOW','IF_CHARGER','IF_ENEMY','IF_WINDUP','UNTIL_GOAL'],requireTypes:['IF_HP_LOW','IF_ENERGY_LOW'],reward:{id:'survival_core',name:'생존 코어',desc:'여러 자원을 보존하며 장기 실행하는 능력을 검증했습니다.'}},
 {arc:'citadel',chapter:'버그 성채 · 보스',concept:'전 개념 종합',title:'ROOT WARDEN',name:'35. 성채의 관리자',text:'ROOT WARDEN은 방어, 강공, 레이저 봉쇄를 바꿔가며 공격합니다. 지금까지 만든 기술과 센서를 모두 활용하세요.',objective:'ROOT WARDEN 격파 후 NULL CORE 진입',start:{x:1,y:0},goal:{x:21,y:0},platforms:floor(23,[10]),switches:[{id:'gate',x:5,y:0}],doors:[{x:7,y:0,switchId:'gate'}],hazards:[{x:12,type:'laser',cycle:['safe','danger','safe','danger']}],enemies:[{x:18,y:0,type:'root_warden',hp:12,boss:true,cycle:['guard','windup','slam','rest','windup','shoot','rest']}],crystals:[],treasures:[{x:20,y:0,id:'citadel_core',name:'성채 루트 키'}],memory:26,functionMemory:12,par:17,totalPar:28,available:['FWD','JUMP','ATTACK','DODGE','WAIT','TOGGLE','IF_SWITCH','IF_GAP','IF_ENEMY','IF_WINDUP','IF_ENEMY_WINDUP','UNTIL_SAFE','UNTIL_GOAL','CALL_FN','CALL_FN_B'],validationTests:[{id:'root_phase',name:'ROOT 패턴 변경',enemies:[{x:18,y:0,type:'root_warden',hp:12,boss:true,cycle:['windup','shoot','rest','guard','windup','slam','rest'],initialStateIndex:2}],hazards:[{x:12,type:'laser',cycle:['danger','safe','danger','safe'],initialStateIndex:1}]}],boss:true,reward:{id:'citadel_core',name:'성채 루트 키',desc:'NULL CORE의 최종 시험이 열립니다.',memoryBonus:4}},

 // NULL CORE · 36~40
 {arc:'null',chapter:'NULL CORE · 1',concept:'범용 이동 AI',title:'알 수 없는 길',name:'36. 맵을 보지 않고도',text:'NULL CORE에서는 검증 지형이 크게 달라집니다. 목적지, 절벽, 위험 신호만 보고 움직이는 범용 이동 코드를 만드세요.',objective:'서로 다른 4개 지형을 같은 코드로 통과',start:{x:1,y:0},goal:{x:17,y:0},platforms:floor(19,[6,12]),hazards:[{x:9,type:'laser',cycle:['safe','danger']}],crystals:[],doors:[],enemies:[],treasures:[],memory:14,par:7,available:['FWD','JUMP','WAIT','IF_GAP','UNTIL_SAFE','UNTIL_GOAL'],requireType:'UNTIL_GOAL',validationTests:[{id:'null_path_a',name:'NULL 지형 A',platforms:floor(19,[4,10,14]),hazards:[{x:7,type:'laser',cycle:['danger','safe']}]},{id:'null_path_b',name:'NULL 지형 B',platforms:floor(19,[8,13]),hazards:[{x:5,type:'laser',cycle:['safe','danger','danger']}]},{id:'null_path_c',name:'NULL 지형 C',platforms:floor(19,[5,11]),hazards:[{x:14,type:'laser',cycle:['danger','safe','safe']}]}],reward:{id:'universal_move_core',name:'범용 이동 코어',desc:'지형이 달라도 같은 이동 로직을 유지합니다.'}},
 {arc:'null',chapter:'NULL CORE · 2',concept:'범용 전투 AI',title:'적을 모르는 전투',name:'37. 종류가 달라도 대응해',text:'적 종류와 시작 패턴이 계속 바뀝니다. 특정 몬스터 순서를 외우지 말고 상태를 읽는 전투 AI를 만드세요.',objective:'3종 전투 배치를 같은 코드로 격파',start:{x:1,y:0},goal:{x:18,y:0},platforms:floor(20),enemies:[{x:6,y:0,type:'robot',hp:2},{x:12,y:0,type:'golem',hp:2,cycle:['idle','windup','slam','rest']}],crystals:[],doors:[],treasures:[],memory:18,par:11,available:['FWD','ATTACK','DODGE','WAIT','IF_ENEMY','IF_WINDUP','IF_ENEMY_WINDUP','UNTIL_GOAL'],validationTests:[{id:'null_fight_a',name:'전투 조합 A',enemies:[{x:5,y:0,type:'spitter',hp:2,cycle:['idle','windup','shoot','rest']},{x:13,y:0,type:'robot',hp:2}]},{id:'null_fight_b',name:'전투 조합 B',enemies:[{x:7,y:0,type:'golem',hp:2,cycle:['rest','idle','windup','slam']},{x:14,y:0,type:'shield',hp:2,cycle:['guard','open','guard','open']}]}],requireType:'IF_ENEMY',reward:{id:'universal_combat_core',name:'범용 전투 코어',desc:'적 종류보다 상태를 보고 대응합니다.'}},
 {arc:'null',chapter:'NULL CORE · 3',concept:'범용 자원 AI',title:'값이 바뀌는 세계',name:'38. 필요한 만큼만 모아',text:'필요 데이터와 충전 위치가 테스트마다 달라집니다. 데이터·에너지·단말기 상태를 함께 관리하세요.',objective:'자원 배치가 달라도 업로드 후 출구로',start:{x:1,y:0},goal:{x:20,y:0},platforms:floor(22),usesEnergy:true,startEnergy:8,rechargeStations:[{x:6,y:0},{x:13,y:0},{x:18,y:0}],dataItems:[{x:3,y:0},{x:5,y:0},{x:9,y:0},{x:12,y:0},{x:16,y:0}],terminals:[{id:'t',x:17,y:0,need:3}],doors:[{x:18,y:0,terminalId:'t'}],crystals:[],enemies:[],treasures:[],memory:20,par:13,available:['FWD','CHARGE','COLLECT_DATA','UPLOAD','IF_DATA','IF_TERMINAL','IF_ENERGY_LOW','IF_CHARGER','UNTIL_GOAL'],requireUploads:1,validationTests:[{id:'null_resource_a',name:'자원 조합 A',startEnergy:9,rechargeStations:[{x:5,y:0},{x:12,y:0},{x:18,y:0}],dataItems:[{x:2,y:0},{x:7,y:0},{x:11,y:0},{x:15,y:0}],terminals:[{id:'t',x:16,y:0,need:3}],doors:[{x:18,y:0,terminalId:'t'}]}],reward:{id:'universal_resource_core',name:'범용 자원 코어',desc:'필요량과 배치가 바뀌어도 상태를 읽어 처리합니다.'}},
 {arc:'null',chapter:'NULL CORE · 4',concept:'통합 프로그램',title:'모든 시스템 동시 가동',name:'39. 하나의 원정 AI',text:'지형, 전투, 스위치, 데이터, 에너지가 한 구역에 모두 등장합니다. 기술 A/B를 역할별로 조합하세요.',objective:'두 기술을 활용해 통합 시험 통과',start:{x:1,y:0},goal:{x:22,y:0},platforms:floor(24,[10]),usesEnergy:true,startEnergy:10,rechargeStations:[{x:8,y:0},{x:17,y:0}],switches:[{id:'a',x:4,y:0}],doors:[{x:6,y:0,switchId:'a'},{x:19,y:0,terminalId:'t'}],dataItems:[{x:12,y:0},{x:14,y:0},{x:16,y:0}],terminals:[{id:'t',x:18,y:0,need:3}],hazards:[{x:9,type:'laser',cycle:['safe','danger']}],enemies:[{x:7,y:0,type:'robot',hp:1},{x:20,y:0,type:'golem',hp:2,cycle:['idle','windup','slam','rest']}],crystals:[],treasures:[],memory:24,functionMemory:12,par:16,totalPar:30,available:['FWD','JUMP','ATTACK','DODGE','WAIT','TOGGLE','CHARGE','COLLECT_DATA','UPLOAD','IF_SWITCH','IF_DATA','IF_TERMINAL','IF_ENEMY','IF_WINDUP','IF_GAP','IF_ENERGY_LOW','IF_CHARGER','UNTIL_SAFE','UNTIL_GOAL','CALL_FN','CALL_FN_B'],requireFunctionB:true,requireTypes:['CALL_FN','CALL_FN_B'],reward:{id:'ranger_master',name:'코드 원정대 마스터 코어',desc:'최종 NULL CORE와 맞설 준비가 끝났습니다.'}},
 {arc:'null',chapter:'NULL CORE · 최종',concept:'범용 AI 최종전',title:'NULL CORE',name:'40. 세계의 마지막 버그',text:'마지막 시험에는 고정 정답이 없습니다. 환경과 보스 상태를 읽고, 여러 테스트 세계에서도 살아남는 프로그램을 완성하세요.',objective:'모든 검증 세계에서 NULL CORE 격파',start:{x:1,y:0},goal:{x:23,y:0},platforms:floor(25,[9]),usesEnergy:true,startEnergy:10,rechargeStations:[{x:7,y:0},{x:14,y:0},{x:18,y:0}],switches:[{id:'seal',x:4,y:0}],doors:[{x:6,y:0,switchId:'seal'},{x:19,y:0,terminalId:'root'}],dataItems:[{x:10,y:0},{x:13,y:0},{x:16,y:0}],terminals:[{id:'root',x:18,y:0,need:3}],hazards:[{x:8,type:'laser',cycle:['safe','danger','danger','safe']}],enemies:[{x:21,y:0,type:'null_core',hp:14,boss:true,cycle:['guard','windup','shoot','rest','windup','slam','rest']}],crystals:[],treasures:[{x:22,y:0,id:'null_core_shard',name:'NULL CORE 조각'}],memory:30,functionMemory:14,par:19,totalPar:34,available:['FWD','BACK','JUMP','HIGH_JUMP','DROP','DASH','ATTACK','DODGE','WAIT','HEAL','TOGGLE','CHARGE','COLLECT_DATA','UPLOAD','IF_SWITCH','IF_DATA','IF_TERMINAL','IF_ENEMY','IF_WINDUP','IF_ENEMY_WINDUP','IF_GAP','IF_HP_LOW','IF_ENERGY_LOW','IF_CHARGER','UNTIL_SAFE','UNTIL_GOAL','UNTIL_ENEMIES_GONE','CALL_FN','CALL_FN_B'],requireFunctionB:true,requireUploads:1,validationTests:[{id:'null_final_a',name:'최종 세계 A',platforms:floor(25,[11]),hazards:[{x:9,type:'laser',cycle:['danger','safe','danger','safe'],initialStateIndex:1}],enemies:[{x:21,y:0,type:'null_core',hp:14,boss:true,cycle:['windup','shoot','rest','guard','windup','slam','rest'],initialStateIndex:2}]},{id:'null_final_b',name:'최종 세계 B',platforms:floor(25,[8]),hazards:[{x:7,type:'laser',cycle:['safe','danger','safe','danger'],initialStateIndex:2}],enemies:[{x:21,y:0,type:'null_core',hp:14,boss:true,cycle:['windup','slam','rest','windup','shoot','rest','guard'],initialStateIndex:3}]}],boss:true,reward:{id:'null_core',name:'NULL CORE 정화 배지',desc:'버그월드의 모든 코딩 원정을 완료했습니다.',memoryBonus:5}}
];

const regions=[
 {id:'prologue',name:'코드 캠프',subtitle:'입단 시험',start:0,end:9,icon:'⌘',x:10,y:64},
 {id:'forest',name:'버섯 숲',subtitle:'상태와 분기',start:10,end:14,icon:'♣',x:25,y:43,requiresMission:9},
 {id:'mine',name:'수정 광산',subtitle:'조건 반복',start:15,end:19,icon:'◆',x:40,y:62,requiresMission:14},
 {id:'city',name:'기계 도시',subtitle:'다중 함수와 상태',start:20,end:24,icon:'⚙',x:55,y:38,requiresMission:19},
 {id:'desert',name:'데이터 사막',subtitle:'변수와 자원',start:25,end:29,icon:'▤',x:69,y:62,requiresMission:24},
 {id:'citadel',name:'버그 성채',subtitle:'종합 검증',start:30,end:34,icon:'▥',x:82,y:39,requiresMission:29},
 {id:'null',name:'NULL CORE',subtitle:'최종 범용 AI',start:35,end:39,icon:'◉',x:91,y:67,requiresMission:34}
];

window.CodeQuestData={blocks:A,missions:M,regions};
})();