function actionData(){
 const p=state.place,a=[];
 if(p==='beach'){a.push(A('🔎','해변 수색','부품과 천, 나무를 찾는다','1.25h · 피로 +9',beachSearch),A('🗺️','해안선 조사','바위 만 길과 조류 흔적을 찾는다','2h · 피로 +16',()=>scout('beach')),A('🆘','큰 SOS 표식 만들기','멀리서도 보이는 구조 표식','나무3 · 돌3',()=>build('sos'),()=>state.built.sos?'이미 만들었어요':null))}
 if(p==='camp'){a.push(A('🌿','휴식','피로를 크게 낮춘다','1.5h',rest),A('🥤','물 마시기','체력과 피로를 조금 회복','.5 물',drink),A('🍲','식사','체력을 회복한다','.5 식량',eat),A('⛺','거처 보강','밤의 피로 증가를 줄인다','나무3 · 덩굴1',()=>build('shelter'),()=>state.built.shelter>=2?'최대 보강 완료':null),A('🌧️','빗물 저장통','비 오는 날 자동 식수 확보','나무2 · 천1',()=>build('rain'),()=>state.built.rain?'이미 만들었어요':null),A('🔥','안전한 화덕','야영 기반 시설','나무2 · 돌2',()=>build('fire'),()=>state.built.fire?'이미 만들었어요':null),A('🌱','작은 밭 만들기','정착형 식량 생산','나무2 · 돌2',()=>build('field'),()=>state.built.field?'이미 만들었어요':!state.unlocked.stream?'계곡을 먼저 발견하세요':null),A('🌾','밭 돌보기','배수와 햇빛을 골라 씨앗 심기','미니게임',startFarm,()=>!state.built.field?'밭이 필요해요':null),A('🐟','건조대 만들기','식량 기반을 안정시킨다','나무3 · 덩굴2',()=>build('drying'),()=>state.built.drying?'이미 만들었어요':null),A('🏡','섬에 정착하기','현재 생활 방식으로 정착 엔딩','8일 이후',settle))}
 if(p==='forest'){a.push(A('🧺','숲 채집','자원과 생태를 함께 선택','미니게임',startGather),A('🗺️','숲 안쪽 조사','계곡을 찾고 재료를 확보','2h · 피로 +16',()=>scout('forest')))}
 if(p==='stream')a.push(A('💧','식수 확보','물을 안전하게 끓이거나 정수한다','1.25h · 물 +2.5',collectWater),A('🪨','돌 채집','시설 제작에 쓸 돌을 고른다','1h · 피로 +8',()=>{addItem('stone',2);advance(1,8);log('계곡에서 단단한 돌을 골랐다. +돌 2');render()}));
 if(p==='cove')a.push(A('🎣','낚시','물때와 타이밍을 읽어 낚는다','미니게임',startFishing,()=>!state.tools.rod?'낚싯대가 필요해요':weather().n==='강풍'?'강풍에는 위험해요':null),A('🪨','해안 바위 조사','금속 조각과 씨앗을 찾는다','1.5h',()=>{addItem('metal',1);addItem('seed',1);advance(1.5,10);log('바위 틈에서 금속 조각과 씨앗을 찾았다.');render()}),A('⛵','난파 어선 수리','절벽에서 위치를 확인한 어선을 고친다','금속4 · 나무4 · 천1',()=>startRepair('boat'),()=>!state.wreck?'먼저 높은 곳에서 어선 위치를 확인하세요':state.tools.boat?'수리 완료':state.skills.repair<2?'수리 경험 2가 필요해요':null),A('🌊','수리한 어선으로 출항','물 3 · 식량 3을 싣고 떠난다','즉시 엔딩',()=>{if(!state.tools.boat||state.water<3||state.food<3)return toast('수리한 어선과 물·식량 3이 필요해요.');finish('boat')},()=>!state.tools.boat?'어선을 먼저 수리하세요':null));
 if(p==='cliff')a.push(A('🔭','수평선 정찰','등대와 어선 위치를 확인한다','2h · 피로 +16',()=>scout('cliff')),A('✨','반사 신호 보내기','반사판이 있으면 구조도 상승','1h',()=>{if(!state.tools.mirror)return toast('반사 신호판이 필요해요.');state.rescue=clamp(state.rescue+10,0,100);advance(1,7);log('절벽에서 반사 신호를 보냈다.');render()}));
 if(p==='lighthouse')a.push(A('🔧','등대 장치 수리','멀리 닿는 구조 신호를 만든다','금속3 · 나무2',()=>startRepair('lighthouse'),()=>state.tools.lighthouse?'수리 완료':state.skills.repair<1?'수리 경험 1이 필요해요':null),A('📡','구조 신호 보내기','등대·SOS를 이용해 신호 반복','1h',signal),A('📻','낡은 무전기 수리','전파로 위치를 알린다','금속2 · 건전지1',()=>startRepair('radio'),()=>state.tools.radio?'수리 완료':null));
 return a;
}
function A(icon,title,desc,cost,run,lock){return{icon,title,desc,cost,run,lock}}
function renderActions(){const box=$('#actionList');box.innerHTML='';for(const a of actionData()){const reason=a.lock&&a.lock();const b=document.createElement('button');b.className='action-btn';b.disabled=!!reason;b.innerHTML=`<span class="ico">${a.icon}</span><span><b>${a.title}</b><small>${reason||a.desc}</small></span><span class="action-cost">${a.cost}</span>`;b.onclick=a.run;box.appendChild(b)}}
function render(){if(!state)return;const w=weather();$('#dayText').textContent=`DAY ${state.day} · ${fmtTime(state.time)}`;$('#weatherText').textContent=`${w.i} ${w.n} · 생태 ${state.eco}`;setMeter('hp',state.hp,100);setMeter('water',state.water,6);setMeter('food',state.food,6);setMeter('fatigue',state.fatigue,100,true);setMeter('rescue',state.rescue,100);$('#waterText').textContent=state.water.toFixed(1);$('#foodText').textContent=state.food.toFixed(1);$('#hpText').textContent=Math.round(state.hp);$('#fatigueText').textContent=Math.round(state.fatigue);$('#rescueText').textContent=Math.round(state.rescue)+'%';
 const p=PLACE[state.place];$('#placeIcon').textContent=p.icon;$('#placeName').textContent=p.name;$('#placeDesc').textContent=p.desc;$$('.place-node').forEach(n=>{const id=n.dataset.place;n.classList.toggle('locked',!state.unlocked[id]);n.classList.toggle('current',id===state.place)});const mark=$('#playerMarker');mark.style.left=p.xy[0]+'%';mark.style.top=p.xy[1]+'%';renderActions();renderInventory();renderLog();renderMilestones();$('#objective').textContent=currentObjective();
 $$('.place-node').forEach(n=>n.onclick=()=>move(n.dataset.place));
 if(state.tools.lighthouse&&!state.ended&&state.rescue>=100)finish('lighthouse');
}
function setMeter(id,v,max,reverse=false){const pct=clamp(v/max*100,0,100);$(`#${id}Bar`).style.width=pct+'%';$(`#${id}Bar`).style.background=reverse?(pct>80?'var(--red)':pct>55?'var(--amber)':'var(--teal)'):(pct<25?'var(--red)':pct<50?'var(--amber)':'var(--teal)')}
function renderInventory(){const box=$('#inventory');box.innerHTML=Object.entries(ITEM).map(([k,m])=>`<div class="inv"><span>${m[0]}</span><b>${state.inv[k]||0}</b><small>${m[1]}</small></div>`).join('')}
function renderLog(){const box=$('#log');box.innerHTML=state.logs.map(x=>`<div class="log-entry"><time>D${x.d} ${fmtTime(x.t)}</time>${x.msg}</div>`).join('');$('#logCount').textContent=`${state.logs.length}개 기록`}
function renderMilestones(){const ms=[['💧','안전한 식수원 발견',state.unlocked.stream],['🧵','절벽에 오를 밧줄 제작',state.inv.rope>0],['🎣','낚싯대 수리',state.tools.rod],['🌧️','빗물 저장통 구축',state.built.rain],['🌱','작은 밭 조성',state.built.field],['🧗','바람 절벽 도달',state.unlocked.lighthouse],['📡','구조 신호 50% 이상',state.rescue>=50]];$('#milestones').innerHTML=ms.map(m=>`<div class="milestone ${m[2]?'done':''}"><span>${m[0]}</span><span>${m[1]}</span><b>${m[2]?'✓':'·'}</b></div>`).join('')}
