function currentObjective(){if(!state.unlocked.stream)return'숲 안쪽을 조사해 식수원을 찾자.';if(state.inv.rope<=0)return'덩굴을 모아 밧줄을 만들고 높은 곳을 노리자.';if(!state.unlocked.cliff)return'숲을 더 조사해 바람 절벽으로 가는 길을 찾자.';if(!state.unlocked.lighthouse)return'밧줄을 들고 바람 절벽으로 올라가 수평선을 정찰하자.';if(state.rescue<50)return'등대·SOS·반사판으로 구조 신호를 키우자.';return'구조를 기다릴지, 섬에 정착할지 결정하자.'}
function openModal(title,kicker,html){$('#modalTitle').textContent=title;$('#modalKicker').textContent=kicker;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){clearInterval(fishTimer);fishTimer=null;$('#modal').classList.add('hidden')}
function showGuide(){openModal('게임 방법','HOW TO SURVIVE',`<p><b>1. 지도에서 직접 이동합니다.</b> 이동에도 30분과 피로가 듭니다.</p><p><b>2. 하루가 지나면 물·식량이 자동 소비됩니다.</b> 오늘 필요한 것만 보지 말고 내일 아침을 준비하세요.</p><p><b>3. 자원은 사슬처럼 연결됩니다.</b> 덩굴→밧줄→절벽→등대, 금속+덩굴→낚싯대→생선처럼 다음 행동을 엽니다.</p><p><b>4. 완벽한 선택은 없습니다.</b> 구조를 서두르면 생활 기반을 약해지고, 정착에 투자하면 구조 신호가 늦어집니다.</p><p><b>5. 10가지 엔딩</b>은 플레이 방식에 따라 달라집니다.</p>`)}
function showEndings(){const got=endingList();openModal('엔딩 도감',`${got.length} / 10 DISCOVERED`,`<div class="ending-grid">${Object.entries(ENDINGS).map(([id,e])=>`<div class="ending-card ${got.includes(id)?'':'locked'}"><div style="font-size:1.8rem">${got.includes(id)?e[0]:'❔'}</div><h3>${got.includes(id)?e[1]:'???'}</h3><p>${got.includes(id)?e[3]:endingHint(id)}</p></div>`).join('')}</div>`)}
function endingHint(id){return{radio:'전파를 타고 사람에게 위치를 알린다.',lighthouse:'가장 높은 곳의 빛을 다시 살린다.',boat:'섬을 떠날 준비를 스스로 마친다.',farmer:'땅에서 꾸준한 식량을 만든다.',fisher:'바다를 읽는 기술을 충분히 익힌다.',gatherer:'숲을 해치지 않고 오래 이용한다.',keeper:'등대와 생활 기반을 함께 유지한다.',village:'여러 시설이 서로 이어지는 생활터를 만든다.',researcher:'섬에 대한 지식을 많이 남긴다.',survivor:'오래 버텨 수색의 기회를 만난다.'}[id]}
function showStart(){state=null;$('#gameScreen').classList.add('hidden');$('#startScreen').classList.remove('hidden');const s=load();$('#continueBtn').classList.toggle('hidden',!s);$('#endingCollection').textContent=`발견한 엔딩 ${endingList().length} / 10`}
function start(diff){selectedDiff=diff;state=fresh(diff);$('#startScreen').classList.add('hidden');$('#gameScreen').classList.remove('hidden');closeModal();render();save(true)}
function resume(){const s=load();if(!s)return start(selectedDiff);state=s;selectedDiff=s.difficulty;$('#startScreen').classList.add('hidden');$('#gameScreen').classList.remove('hidden');render()}

$$('#difficulty button').forEach(b=>b.onclick=()=>{$$('#difficulty button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedDiff=b.dataset.diff});
$('#newBtn').onclick=()=>start(selectedDiff);$('#continueBtn').onclick=resume;$('#saveBtn').onclick=()=>save(false);$('#guideBtn').onclick=showGuide;$('#homeBtn').onclick=showStart;$('#craftBtn').onclick=openCraft;$('#endingsBtn').onclick=showEndings;$('#modalClose').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});
window.__driftTest={fresh,advance,chooseSettlement,selfSufficiency,getState:()=>state,setState:s=>{state=s;render()},actions:()=>actionData().map(a=>a.title)};
showStart();
