const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');const runtime=fs.readFileSync(path.join(ROOT,'games','high_bridge_builder','bridge-builder.js'),'utf8');const html=fs.readFileSync(path.join(ROOT,'games','high_bridge_builder','index.html'),'utf8');const css=fs.readFileSync(path.join(ROOT,'games','high_bridge_builder','bridge-builder.css'),'utf8');
test('Bridge Builder keeps the scribble-first controls',()=>{assert.match(html,/그냥 다리를 그리세요/);assert.match(html,/id="inkBar"/);assert.doesNotMatch(html,/data-tool="road"/);assert.match(runtime,/function startStroke/);assert.match(runtime,/function extendStroke/);assert.match(runtime,/pointerdown/);assert.match(runtime,/pointermove/)});
test('physics uses a fixed timestep and pause-aware loop',()=>{assert.match(runtime,/FIXED=1\/60/);assert.match(runtime,/while\(S\.acc>=FIXED/);assert.match(runtime,/MAX_STEPS/);assert.match(runtime,/S\.paused/);assert.match(runtime,/registerPauseHandlers/);assert.match(runtime,/S\.acc=0/)});
test('drawn strokes have deck brace roles and bending stiffness',()=>{assert.match(runtime,/role==="deck"/);assert.match(runtime,/function makeBend/);assert.match(runtime,/S\.bends/);assert.match(runtime,/e\.role!=="deck"/);assert.match(runtime,/stiff:role==="deck"/)});
test('crossing strokes snap and split existing segments',()=>{assert.match(runtime,/function nearestEdgeProjection/);assert.match(runtime,/function splitEdge/);assert.match(runtime,/function resolveStructurePoint/);assert.match(runtime,/replaceNodeRefs/);assert.match(runtime,/선이 만나면 자동으로 붙어요/ )});
test('testing requires a real left-to-right deck path',()=>{assert.match(runtime,/function hasDeckPath/);assert.match(runtime,/if\(!hasDeckPath\(false\)\)/);assert.match(runtime,/차가 달릴 길이 왼쪽에서 오른쪽까지 이어져야 해요/);assert.match(runtime,/hasDeckPath\(false\)\)succeed/ )});
test('failure restores the editable bridge',()=>{assert.match(runtime,/function serializeGeometry/);assert.match(runtime,/function loadGeometry/);assert.match(runtime,/S\.snapshot=serializeGeometry/);assert.match(runtime,/if\(S\.snapshot\)loadGeometry\(S\.snapshot\)/)});
test('early stages have enough ink for a road plus reinforcement',()=>{assert.match(runtime,/gap:330,ink:720/);assert.match(runtime,/gap:410,ink:900/);assert.match(runtime,/gap:625,ink:1480/)});
test('mobile play area preserves the canvas aspect ratio',()=>{assert.match(css,/aspect-ratio:12\/7/);assert.match(css,/width:100%!important/);assert.match(html,/bridge-builder\.js\?v=7/)});

test('bridge routing is recomputed from the finished structure',()=>{assert.match(runtime,/function findBuildDeckRoute/);assert.match(runtime,/function refreshDeckRoles/);assert.match(runtime,/refreshDeckRoles\(\);if\(!hasDeckPath/);assert.match(runtime,/Math\.hypot\(n\.x-b\.leftAnchor\.x,n\.y-b\.leftAnchor\.y\)<5/)});
test('bank supports pin naturally and physics uses accumulated damage',()=>{assert.match(runtime,/function bankPinNear/);assert.match(runtime,/var g=bankPinNear\(p\)/);assert.match(runtime,/damage:0/);assert.match(runtime,/se\.damage=.*\.022/);assert.match(runtime,/for\(var iter=0;iter<10;iter\+\+\)/);assert.doesNotMatch(runtime,/if\(e\.strain>L\.breakRatio\)\{e\.broken=true/)});
