import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone as skeletonClone} from 'three/addons/utils/SkeletonUtils.js';
const $=id=>document.getElementById(id),S=window.EMERGENCY_SCENARIOS||[];
const ui={canvas:$('scene3d'),challenge:$('challenge'),command:$('command'),title:$('title'),prompt:$('prompt'),interaction:$('interaction'),domain:$('domainChip'),round:$('roundText'),score:$('scoreText'),lives:$('livesText'),timer:$('timerBar'),feedback:$('feedback'),feedbackIcon:$('feedbackIcon'),feedbackTitle:$('feedbackTitle'),feedbackText:$('feedbackText'),feedbackSource:$('feedbackSource'),next:$('nextBtn'),menu:$('menu'),result:$('result'),resultTitle:$('resultTitle'),finalScore:$('finalScore'),correctCount:$('correctCount'),bestStreak:$('bestStreak'),review:$('review'),avatar:$('playerAvatar'),avatarFallback:$('avatarFallback')};
let config={mode:'quick',diff:'normal'},state=null,timerRAF=0,deadline=0,locked=false,sequenceStep=0,rhythmTimes=[];const DIFF={easy:10,normal:8,hard:6};
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function gameSound(k){try{window.KidscadeGame?.sound?.(k)}catch(_){}}function safeStart(){try{window.KidscadeGame?.start?.()}catch(_){}}function safeScore(v){try{window.KidscadeGame?.score?.(v)}catch(_){}}function safeGameOver(v){try{window.KidscadeGame?.gameOver?.({score:v})}catch(_){}}
document.querySelectorAll('.modeBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.modeBtn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');config.mode=b.dataset.mode});document.querySelectorAll('.diffBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.diffBtn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');config.diff=b.dataset.diff});$('startBtn').onclick=startRun;$('retryBtn').onclick=()=>{ui.result.classList.remove('show');ui.menu.classList.add('show')};ui.next.onclick=nextScenario;
function startRun(){const pool=config.mode==='full'?shuffle(S):shuffle(S).slice(0,15);state={pool,index:-1,score:0,lives:3,correct:0,streak:0,best:0,misses:[]};ui.menu.classList.remove('show');ui.result.classList.remove('show');safeStart();nextScenario()}
function nextScenario(){cancelAnimationFrame(timerRAF);ui.feedback.classList.add('hidden');ui.feedback.classList.remove('bad');locked=false;sequenceStep=0;rhythmTimes=[];state.index++;if(state.index>=state.pool.length||state.lives<=0)return finishRun();const sc=state.pool[state.index];state.current=sc;renderHUD();renderScenario(sc);setupScene(sc.scene);startTimer(sc)}
function renderHUD(){ui.round.textContent=(state.index+1)+'/'+state.pool.length;ui.score.textContent=state.score;ui.lives.textContent='♥'.repeat(Math.max(0,state.lives))+'♡'.repeat(Math.max(0,3-state.lives))}
function renderScenario(sc){ui.challenge.classList.remove('hidden');ui.command.textContent=sc.mode==='rhythm'?'리듬 맞춰!':sc.mode==='sequence'?'순서대로!':'판단해!';ui.title.textContent=sc.title;ui.prompt.textContent=sc.prompt;ui.domain.textContent=sc.domain;ui.interaction.innerHTML='';if(sc.mode==='sequence')return renderSequence(sc);if(sc.mode==='rhythm')return renderRhythm(sc);shuffle(sc.options).forEach((o,i)=>{const b=document.createElement('button');b.className='answer';b.type='button';b.textContent=(i+1)+'. '+o.label;b.onclick=()=>answerChoice(o,b,sc);ui.interaction.appendChild(b)})}
function renderSequence(sc){const step=sc.steps[sequenceStep];ui.prompt.textContent=step.prompt;const head=document.createElement('div');head.className='sequenceHead';head.textContent=(sequenceStep+1)+' / '+sc.steps.length+' 단계';ui.interaction.appendChild(head);shuffle(step.options).forEach((o,i)=>{const b=document.createElement('button');b.className='answer';b.type='button';b.textContent=(i+1)+'. '+o.label;b.onclick=()=>answerSequence(o,b,sc);ui.interaction.appendChild(b)})}
function answerSequence(o,b,sc){if(locked)return;if(!o.correct)return resolve(false,sc,b);b.classList.add('correct');sequenceStep++;if(sequenceStep>=sc.steps.length)return resolve(true,sc,b);gameSound('correct');setTimeout(()=>{ui.interaction.innerHTML='';renderSequence(sc)},260)}
function renderRhythm(sc){const box=document.createElement('div');box.className='rhythmBox';const read=document.createElement('div');read.className='rhythmReadout';read.textContent='0 / '+sc.presses+'회 · 목표 100~120회/분';const b=document.createElement('button');b.className='rhythmBtn';b.type='button';b.textContent='가슴 압박';b.onclick=()=>rhythmPress(sc,read,b);box.append(read,b);ui.interaction.appendChild(box)}
function rhythmPress(sc,read,b){if(locked)return;const now=performance.now();rhythmTimes.push(now);b.animate([{transform:'translateY(7px) scale(.98)'},{transform:'none'}],{duration:120});let bpm=0;if(rhythmTimes.length>2){const dt=(now-rhythmTimes[0])/(rhythmTimes.length-1);bpm=Math.round(60000/dt)}read.textContent=rhythmTimes.length+' / '+sc.presses+'회'+(bpm?' · '+bpm+'회/분':'')+' · 목표 100~120';if(rhythmTimes.length>=sc.presses){const intervals=rhythmTimes.slice(1).map((t,i)=>t-rhythmTimes[i]);const avg=intervals.reduce((a,v)=>a+v,0)/intervals.length,val=60000/avg;resolve(val>=sc.targetBpm[0]&&val<=sc.targetBpm[1],sc,b,'측정 '+Math.round(val)+'회/분')}}
function answerChoice(o,b,sc){if(locked)return;resolve(!!o.correct,sc,b)}
function resolve(ok,sc,button,extra=''){if(locked)return;locked=true;cancelAnimationFrame(timerRAF);document.querySelectorAll('.answer').forEach(x=>x.disabled=true);if(button)button.classList.add(ok?'correct':'wrong');if(ok){state.correct++;state.streak++;state.best=Math.max(state.best,state.streak);const remain=Math.max(0,deadline-performance.now());state.score+=100+Math.round(remain/120);gameSound('correct')}else{state.lives--;state.streak=0;state.misses.push(sc);gameSound('wrong')}safeScore(state.score);renderHUD();setTimeout(()=>showFeedback(ok,sc,extra),320)}
function showFeedback(ok,sc,extra){ui.challenge.classList.add('hidden');ui.feedback.classList.remove('hidden');ui.feedback.classList.toggle('bad',!ok);ui.feedbackIcon.textContent=ok?'✓':'!';ui.feedbackTitle.textContent=ok?'좋은 판단!':'이 행동을 기억해!';ui.feedbackText.textContent=(extra?extra+' · ':'')+sc.rationale;ui.feedbackSource.textContent=sc.source?'근거: '+sc.source:''}
function timeout(){if(locked)return;resolve(false,state.current,null,'시간 초과')}
function startTimer(sc){const base=sc.mode==='sequence'?Math.max(14,DIFF[config.diff]+7):sc.mode==='rhythm'?14:DIFF[config.diff];deadline=performance.now()+base*1000;function tick(){if(locked)return;const left=deadline-performance.now();ui.timer.style.transform='scaleX('+Math.max(0,left/(base*1000))+')';if(left<=0)return timeout();timerRAF=requestAnimationFrame(tick)}tick()}
function finishRun(){cancelAnimationFrame(timerRAF);ui.challenge.classList.add('hidden');ui.feedback.classList.add('hidden');ui.result.classList.add('show');ui.finalScore.textContent=state.score;ui.correctCount.textContent=state.correct+'/'+state.pool.length;ui.bestStreak.textContent=state.best;ui.resultTitle.textContent=state.lives>0?'위기 대응 완료!':'훈련 종료!';ui.review.innerHTML=state.misses.length?state.misses.slice(0,8).map(x=>'<div class="reviewItem"><b>'+escapeHtml(x.title)+'</b> · '+escapeHtml(x.rationale)+'</div>').join(''):'<div class="reviewItem"><b>모든 상황을 정확히 판단했어요.</b></div>';safeGameOver(state.score)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
addEventListener('keydown',e=>{if(!state||locked)return;if(state.current?.mode==='rhythm'&&e.code==='Space'){e.preventDefault();ui.interaction.querySelector('.rhythmBtn')?.click();return}const n=Number(e.key);if(n>=1&&n<=4)ui.interaction.querySelectorAll('.answer')[n-1]?.click()});
function avatarHost(){try{if(parent&&parent!==window&&parent.location.origin===location.origin)return parent}catch(_){}return window}function avatarApi(){const h=avatarHost();for(const f of [()=>window.KidscadeAvatarShop,()=>h.KidscadeAvatarShop,()=>h.document?.getElementById('kidscade-avatar-studio-frame')?.contentWindow?.KidscadeAvatarShop]){try{const a=f();if(a&&typeof a.renderPreviewFrame==='function')return a}catch(_){}}return null}setInterval(()=>{const a=avatarApi();if(!a)return;try{const src=a.renderPreviewFrame('idle',performance.now()/1000);if(src&&src.startsWith('data:image')){ui.avatar.src=src;ui.avatar.style.display='block';ui.avatarFallback.style.display='none'}}catch(_){}},180);
const renderer=new THREE.WebGLRenderer({canvas:ui.canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();scene.background=new THREE.Color(0x10243d);scene.fog=new THREE.Fog(0x10243d,18,42);const camera=new THREE.PerspectiveCamera(48,1,.1,100);camera.position.set(0,5.4,10.5);camera.lookAt(0,1.2,0);scene.add(new THREE.HemisphereLight(0xcfe8ff,0x243019,2));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(-5,10,6);sun.castShadow=true;scene.add(sun);const stage=new THREE.Group();scene.add(stage);const loader=new GLTFLoader(),cache=new Map();
const ASSET={person:'../../assets/game/characters/people/character-male-a.glb',person2:'../../assets/game/characters/people/character-female-b.glb',aed:'../../assets/game/props/accessibility/aid-defibrillator-red.glb',ambulance:'../../assets/game/3d/vehicles/kenney-car-kit/ambulance.glb',firetruck:'../../assets/game/3d/vehicles/kenney-car-kit/firetruck.glb',traffic:'../../assets/game/3d/city/kenney-city-kit-roads/traffic-light.glb',road:'../../assets/game/3d/city/kenney-city-kit-roads/road-straight.glb',barrier:'../../assets/game/3d/city/kenney-city-kit-roads/construction-barrier.glb',oven:'../../assets/game/3d/interiors/modular-sushi-restaurant-kit/oven.glb',chair:'../../assets/game/3d/interiors/modular-sushi-restaurant-kit/chair.glb',table:'../../assets/game/3d/interiors/modular-sushi-restaurant-kit/table.glb',tree:'../../assets/game/3d/nature/kenney-nature-kit/tree-default.glb',rock:'../../assets/game/3d/nature/kenney-nature-kit/rock-large.glb',door:'../../assets/quaternius_cc0-door-925.glb',stairs:'../../assets/quaternius_cc0-stairs-1374.glb',washer:'../../assets/quaternius_cc0-washing-machine-681.glb'};
const SCENES={classroomFire:[['person',-1.6,0,0,1.6],['chair',1.5,0,.4,1.4],['table',1.5,0,-1.3,1.2]],schoolFire:[['person',-1.4,0,.3,1.6],['door',1.8,0,-.8,1.4]],stairs:[['person',-1.7,0,.2,1.6],['stairs',1.5,0,-1,1.9]],personFire:[['person',0,0,.2,1.7]],homeFire:[['person',-1.5,0,.2,1.6],['door',1.8,0,-.8,1.4]],kitchenFire:[['person',-1.7,0,.4,1.6],['oven',1.2,0,-.8,1.7]],kitchen:[['person',-1.7,0,.4,1.6],['oven',1.2,0,-.8,1.7]],electric:[['person',-1.5,0,.2,1.6],['washer',1.4,0,-.6,1.5]],electricFire:[['person',-1.5,0,.2,1.6],['washer',1.4,0,-.6,1.5]],earthquakeClass:[['person',-1.6,0,.4,1.6],['table',1,0,-.8,1.4],['chair',2.1,0,.5,1.4]],earthquakeWindow:[['person',0,0,.2,1.7]],earthquakeStreet:[['person',-1.2,0,.2,1.6],['traffic',1.8,0,-1,1.7]],stormHome:[['person',0,0,.2,1.7]],lightning:[['person',-1.4,0,.3,1.6],['tree',1.7,0,-1,2.3]],river:[['person',-1.4,0,.2,1.6],['tree',1.7,0,-1,2],['rock',.6,0,.2,1.5]],floodRoad:[['person',-1.5,0,.3,1.6],['road',1.4,0,-1,2]],floodGarage:[['person',0,0,.3,1.7]],heat:[['person',-1,0,.3,1.6],['person2',1,0,.1,1.6]],cold:[['person',0,0,.2,1.7]],crosswalk:[['person',-1.4,0,.3,1.6],['traffic',1.6,0,-1,1.8],['road',0,0,-1.6,2]],crosswalkCar:[['person',-1.4,0,.3,1.6],['traffic',1.6,0,-1,1.8],['road',0,0,-1.6,2]],roadBall:[['person',-1.2,0,.3,1.6],['road',1.2,0,-1.5,2]],parkedCars:[['person',0,0,.4,1.7],['road',0,0,-1.5,2]],bike:[['person',0,0,.3,1.7]],busStop:[['person',0,0,.2,1.7],['barrier',1.8,0,-.8,1.5]],carDoor:[['person',0,0,.2,1.7],['road',0,0,-1.5,2]],rail:[['person',-1.4,0,.2,1.6],['barrier',1.4,0,-.6,1.8]],parking:[['person',0,0,.2,1.7],['road',0,0,-1.6,2]],carSeat:[['person',0,0,.2,1.7]],waterRescue:[['person',-1.6,0,.3,1.6],['person2',1.5,-.15,-1.5,1.5]],water:[['person',0,0,.3,1.7],['tree',2,0,-1,2]],ice:[['person',0,0,.3,1.7]],cpr:[['person2',0,0,.2,1.8],['aed',2.2,0,-.4,1.8],['ambulance',-2.6,0,-2.3,1.8]],aed:[['person2',0,0,.2,1.8],['aed',2.1,0,-.2,2]],choking:[['person',-1,0,.3,1.7],['person2',1,0,.2,1.7],['table',0,0,-1.2,1.3]],infant:[['person',0,0,.3,1.7]],burn:[['person',-1.2,0,.3,1.7],['oven',1.3,0,-.7,1.6]],electricShock:[['person',-1.1,0,.2,1.7],['washer',1.3,0,-.6,1.5]]};
function baseStage(){while(stage.children.length)stage.remove(stage.children[0]);const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,12),new THREE.MeshStandardMaterial({color:0x405b43,roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;stage.add(floor);for(let i=-2;i<=2;i++){const line=new THREE.Mesh(new THREE.BoxGeometry(.04,.01,10),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.08}));line.position.set(i*2,.01,0);stage.add(line)}}
async function model(key,x,y,z,target=1.5){const url=ASSET[key];if(!url)return;let g=cache.get(url);if(!g){try{g=await loader.loadAsync(url);cache.set(url,g)}catch(_){return}}let obj;try{obj=skeletonClone(g.scene)}catch(_){obj=g.scene.clone(true)}let box=new THREE.Box3().setFromObject(obj),size=box.getSize(new THREE.Vector3()),max=Math.max(size.x,size.y,size.z)||1;obj.scale.setScalar(target/max);box=new THREE.Box3().setFromObject(obj);const c=box.getCenter(new THREE.Vector3());obj.position.set(x-c.x,y-box.min.y,z-c.z);obj.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});stage.add(obj)}
function setupScene(key){baseStage();scene.fog.color.set(0x10243d);scene.background.set(0x10243d);const arr=SCENES[key]||[['person',0,0,0,1.7]];arr.forEach(a=>model(...a));if(/Fire|fire/.test(key))addFire();if(/earthquake/.test(key))shakeUntil=performance.now()+1400;if(/flood|river|waterRescue|water$/.test(key))addWater();if(key==='lightning')flashUntil=performance.now()+900;if(key==='ice')addIce()}
function addFire(){for(let i=0;i<7;i++){const m=new THREE.Mesh(new THREE.ConeGeometry(.18+Math.random()*.2,.8+Math.random()*.6,8),new THREE.MeshBasicMaterial({color:i%2?0xff8a00:0xffd000,transparent:true,opacity:.84}));m.position.set(.7+Math.random()*1.5,.4,-.7+Math.random()*.8);stage.add(m)}}function addWater(){const w=new THREE.Mesh(new THREE.PlaneGeometry(18,5),new THREE.MeshStandardMaterial({color:0x248bd6,transparent:true,opacity:.72,roughness:.25}));w.rotation.x=-Math.PI/2;w.position.set(0,.07,-1.8);stage.add(w)}function addIce(){const w=new THREE.Mesh(new THREE.PlaneGeometry(12,6),new THREE.MeshStandardMaterial({color:0xbfeaff,transparent:true,opacity:.78,roughness:.15}));w.rotation.x=-Math.PI/2;w.position.y=.04;stage.add(w)}
let shakeUntil=0,flashUntil=0;function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();function loop(t){if(t<shakeUntil){camera.position.x=Math.sin(t*.08)*.08;camera.position.y=5.4+Math.cos(t*.11)*.05}else{camera.position.x=0;camera.position.y=5.4}renderer.setClearColor(t<flashUntil?0xdff5ff:0x10243d);renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
