(function(){
"use strict";
var canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),W=1200,H=700,TAU=Math.PI*2;
var el={stageTitle:document.getElementById("stageTitle"),stageGoal:document.getElementById("stageGoal"),prev:document.getElementById("prevLevel"),next:document.getElementById("nextLevel"),help:document.getElementById("helpBtn"),inkBar:document.getElementById("inkBar"),inkText:document.getElementById("inkText"),vehicle:document.getElementById("vehicleText"),hint:document.getElementById("hint"),toast:document.getElementById("toast"),test:document.getElementById("testBtn"),undo:document.getElementById("undoBtn"),reset:document.getElementById("resetBtn"),result:document.getElementById("resultCard"),resultIcon:document.getElementById("resultIcon"),resultTitle:document.getElementById("resultTitle"),resultText:document.getElementById("resultText"),stars:document.getElementById("stars"),retry:document.getElementById("retryBtn"),cont:document.getElementById("continueBtn"),tutorial:document.getElementById("tutorial"),tutorialClose:document.getElementById("tutorialClose")};
var VEHICLES={sedan:{label:"승용차",emoji:"🚗",mass:.82,speed:116},bus:{label:"스쿨버스",emoji:"🚌",mass:1.04,speed:100},ambulance:{label:"구급차",emoji:"🚑",mass:.96,speed:110},firetruck:{label:"소방차",emoji:"🚒",mass:1.18,speed:92},truck:{label:"대형 화물차",emoji:"🚚",mass:1.36,speed:82}};
var LEVELS=[
 {title:"1. 작은 개울",goal:"노란 점 사이를 손가락으로 이어 보세요",gap:330,ink:520,vehicle:"sedan",breakRatio:1.22,gravity:.31,tip:"처음에는 한 줄로도 건널 수 있어요."},
 {title:"2. 학교 가는 길",goal:"조금 더 긴 강을 건너 보세요",gap:410,ink:650,vehicle:"bus",breakRatio:1.20,gravity:.32,tip:"많이 처지면 아래에 선을 하나 더 받쳐 보세요."},
 {title:"3. 깊은 골짜기",goal:"긴 다리를 튼튼하게 그려 보세요",gap:485,ink:770,vehicle:"sedan",breakRatio:1.18,gravity:.33,tip:"두 선을 서로 이어 주면 더 안정적이에요."},
 {title:"4. 큰 강",goal:"구급차가 무사히 지나가게 하세요",gap:545,ink:850,vehicle:"ambulance",breakRatio:1.17,gravity:.34,tip:"가운데가 너무 길면 쉽게 처져요."},
 {title:"5. 비바람 다리",goal:"흔들려도 끊어지지 않게 그려 보세요",gap:560,ink:900,vehicle:"bus",breakRatio:1.16,gravity:.35,wind:.018,tip:"아래쪽 보강선을 덧그리면 흔들림이 줄어요."},
 {title:"6. 절약 공사",goal:"적은 선으로 반대편까지 이어 보세요",gap:525,ink:700,vehicle:"sedan",breakRatio:1.17,gravity:.34,tip:"필요한 곳에만 선을 써 보세요."},
 {title:"7. 긴급 출동",goal:"무거운 소방차가 건널 다리를 그리세요",gap:590,ink:980,vehicle:"firetruck",breakRatio:1.15,gravity:.36,tip:"한 줄보다 여러 선이 서로 연결된 구조가 튼튼해요."},
 {title:"8. 초대형 화물",goal:"가장 무거운 화물차를 건너게 하세요",gap:625,ink:1080,vehicle:"truck",breakRatio:1.14,gravity:.37,tip:"짧은 선들을 연결해 힘을 나눠 보세요."}
];
var S={level:0,mode:"build",nodes:[],edges:[],strokes:[],drawing:false,current:null,ink:0,vehicle:null,snapshot:null,toastTimer:0,hintTimer:0,last:performance.now(),broken:0};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function level(){return LEVELS[S.level]}
function banks(){var g=level().gap,cx=W/2;return{leftX:cx-g/2,rightX:cx+g/2,y:405,waterY:525,leftAnchor:{x:cx-g/2,y:395},rightAnchor:{x:cx+g/2,y:395}}}
function showToast(msg){el.toast.textContent=msg;el.toast.classList.add("show");clearTimeout(S.toastTimer);S.toastTimer=setTimeout(function(){el.toast.classList.remove("show")},1250)}
function showHint(msg,fade){clearTimeout(S.hintTimer);el.hint.textContent=msg;el.hint.classList.remove("fade");if(fade!==false)S.hintTimer=setTimeout(function(){el.hint.classList.add("fade")},2400)}
function updateInk(){var r=clamp(S.ink/level().ink,0,1);el.inkBar.style.width=Math.round(r*100)+"%";el.inkText.textContent=Math.round(r*100)+"%"}
function resetLevel(){S.mode="build";S.nodes=[];S.edges=[];S.strokes=[];S.drawing=false;S.current=null;S.ink=level().ink;S.vehicle=null;S.snapshot=null;S.broken=0;el.result.classList.add("hidden");el.stageTitle.textContent=level().title;el.stageGoal.textContent=level().goal;var v=VEHICLES[level().vehicle];el.vehicle.textContent=v.emoji+" "+v.label;el.test.textContent="▶ 시험 운행";updateInk();showHint(level().goal)}
function pointFromEvent(e){var r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function makeNode(x,y,pinned){var n={x:x,y:y,px:x,py:y,pinned:!!pinned};S.nodes.push(n);return n}
function makeEdge(a,b){if(a===b)return null;var e={a:a,b:b,rest:Math.max(2,dist(a,b)),broken:false,strain:1};S.edges.push(e);return e}
function nearestNode(p,radius,exclude){var best=null,bd=radius;for(var i=0;i<S.nodes.length;i++){var n=S.nodes[i];if(n===exclude)continue;var d=Math.hypot(n.x-p.x,n.y-p.y);if(d<bd){bd=d;best=n}}return best}
function anchorNear(p){var b=banks(),r=48;if(Math.hypot(p.x-b.leftAnchor.x,p.y-b.leftAnchor.y)<r)return b.leftAnchor;if(Math.hypot(p.x-b.rightAnchor.x,p.y-b.rightAnchor.y)<r)return b.rightAnchor;return null}
function startStroke(p){if(S.mode!=="build")return;if(S.ink<=2){showToast("남은 선이 없어요");return}var near=nearestNode(p,24,null),a=anchorNear(p),start,created=[];if(near)start=near;else if(a){start=makeNode(a.x,a.y,true);created.push(start)}else{start=makeNode(p.x,p.y,false);created.push(start)}S.current={nodes:[start],edges:[],created:created,used:0};S.drawing=true}
function extendStroke(p){if(!S.drawing||!S.current||S.ink<=0)return;var last=S.current.nodes[S.current.nodes.length-1],d=Math.hypot(p.x-last.x,p.y-last.y);if(d<15)return;var use=Math.min(d,S.ink),t=use/d,nx=last.x+(p.x-last.x)*t,ny=last.y+(p.y-last.y)*t;var n=makeNode(nx,ny,false),e=makeEdge(last,n);S.current.nodes.push(n);S.current.created.push(n);if(e)S.current.edges.push(e);S.current.used+=use;S.ink-=use;updateInk()}
function replaceNode(oldNode,newNode){for(var i=0;i<S.edges.length;i++){if(S.edges[i].a===oldNode)S.edges[i].a=newNode;if(S.edges[i].b===oldNode)S.edges[i].b=newNode}}
function endStroke(){if(!S.drawing||!S.current)return;S.drawing=false;var st=S.current;S.current=null;if(st.nodes.length<2){removeStrokeObjects(st);return}var last=st.nodes[st.nodes.length-1],a=anchorNear(last),near=nearestNode(last,28,last);if(a){last.x=a.x;last.y=a.y;last.px=a.x;last.py=a.y;last.pinned=true}else if(near){replaceNode(last,near);S.nodes=S.nodes.filter(function(n){return n!==last});st.created=st.created.filter(function(n){return n!==last});st.nodes[st.nodes.length-1]=near}S.strokes.push(st);showHint(S.strokes.length===1?"좋아요! 바로 시험해도 돼요. 더 받쳐도 좋아요.":level().tip)}
function removeStrokeObjects(st){if(!st)return;var edgeSet=new Set(st.edges),nodeSet=new Set(st.created);S.edges=S.edges.filter(function(e){return !edgeSet.has(e)});var usedByOther=new Set();for(var i=0;i<S.edges.length;i++){usedByOther.add(S.edges[i].a);usedByOther.add(S.edges[i].b)}S.nodes=S.nodes.filter(function(n){return !nodeSet.has(n)||usedByOther.has(n)});S.ink=Math.min(level().ink,S.ink+(st.used||0));updateInk()}
function undo(){if(S.mode!=="build")return;var st=S.strokes.pop();if(!st){showToast("되돌릴 선이 없어요");return}removeStrokeObjects(st);showToast("마지막 선을 되돌렸어요")}
function clearAll(){if(S.mode!=="build")return;S.nodes=[];S.edges=[];S.strokes=[];S.ink=level().ink;updateInk();showHint("노란 점 사이를 다시 그려 보세요")}
function hasPinnedSide(side){var b=banks(),x=side==="left"?b.leftAnchor.x:b.rightAnchor.x;return S.nodes.some(function(n){return n.pinned&&Math.abs(n.x-x)<3})}
function saveSnapshot(){S.snapshot={nodes:S.nodes.map(function(n){return{n:n,x:n.x,y:n.y,px:n.px,py:n.py}}),edges:S.edges.map(function(e){return{e:e}})}}
function restoreSnapshot(){if(!S.snapshot)return;S.snapshot.nodes.forEach(function(s){s.n.x=s.x;s.n.y=s.y;s.n.px=s.px;s.n.py=s.py});S.snapshot.edges.forEach(function(s){s.e.broken=false;s.e.strain=1});S.broken=0}
function startTest(){if(S.mode==="run")return;if(!S.edges.length){showToast("먼저 다리를 그려 보세요");return}if(!hasPinnedSide("left")||!hasPinnedSide("right")){showToast("양쪽 노란 점에 다리를 붙여 주세요");return}saveSnapshot();S.mode="run";S.broken=0;var b=banks(),v=VEHICLES[level().vehicle];S.vehicle={x:b.leftX-54,y:b.y-24,vy:0,w:54,h:26,speed:v.speed,mass:v.mass};el.test.textContent="시험 중…";showHint("잘 버티나 볼까요?",false);try{window.KidscadeGame?.start?.({level:S.level+1})}catch(_){}}
function fail(msg){if(S.mode!=="run")return;S.mode="build";S.vehicle=null;restoreSnapshot();el.test.textContent="▶ 다시 시험";showToast(msg);showHint(level().tip);try{window.KidscadeGame?.sound?.("wrong")}catch(_){}}
function succeed(){if(S.mode!=="run")return;S.mode="end";var used=level().ink-S.ink,ratio=used/level().ink,stars=ratio<.62?3:ratio<.82?2:1;el.resultIcon.textContent="🏆";el.resultTitle.textContent="통과 성공!";el.resultText.textContent=stars===3?"선도 아끼고 튼튼하게 만들었어요!":"차가 무사히 건넜어요. 더 적은 선으로도 도전해 보세요.";el.stars.textContent="★".repeat(stars)+"☆".repeat(3-stars);el.result.classList.remove("hidden");try{window.KidscadeGame?.score?.((S.level+1)*100+stars*10)}catch(_){}}
function supportAt(x){var b=banks(),best=null,bestY=Infinity;if(x<=b.leftX||x>=b.rightX)return{y:b.y,edge:null,t:0};for(var i=0;i<S.edges.length;i++){var e=S.edges[i];if(e.broken)continue;var ax=e.a.x,bx=e.b.x,min=Math.min(ax,bx),max=Math.max(ax,bx);if(x<min||x>max||max-min<2)continue;var t=(x-ax)/(bx-ax);if(t<0||t>1)continue;var y=e.a.y+(e.b.y-e.a.y)*t;if(y<bestY){bestY=y;best={y:y,edge:e,t:t}}}return best}
function physics(dt){if(S.mode!=="run")return;var L=level(),g=L.gravity,wind=L.wind||0,v=S.vehicle;for(var i=0;i<S.nodes.length;i++){var n=S.nodes[i];if(n.pinned)continue;var vx=(n.x-n.px)*.992+wind*Math.sin((performance.now()+i*137)/650),vy=(n.y-n.py)*.992+g*dt*60;n.px=n.x;n.py=n.y;n.x+=vx;n.y+=vy}for(var iter=0;iter<7;iter++){for(var j=0;j<S.edges.length;j++){var e=S.edges[j];if(e.broken)continue;var dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,len=Math.hypot(dx,dy)||.001;e.strain=len/e.rest;if(e.strain>L.breakRatio){e.broken=true;S.broken++;continue}var diff=(len-e.rest)/len,ox=dx*.5*diff,oy=dy*.5*diff;if(!e.a.pinned){e.a.x+=ox;e.a.y+=oy}if(!e.b.pinned){e.b.x-=ox;e.b.y-=oy}}}if(v){var sup=supportAt(v.x),bottom=v.y+v.h/2;if(sup&&bottom>=sup.y-10&&v.vy>=0){v.y=sup.y-v.h/2;v.vy=0;v.x+=v.speed*dt;if(sup.edge){var push=18*v.mass*dt,ee=sup.edge;if(!ee.a.pinned)ee.a.y+=push*(1-sup.t);if(!ee.b.pinned)ee.b.y+=push*sup.t}}else{v.vy+=820*dt;v.y+=v.vy*dt}var b=banks();if(v.x>b.rightX+58){succeed();return}if(v.y>b.waterY+100){fail(S.broken?"다리가 끊어졌어요. 아래쪽을 한 줄 더 받쳐 보세요.":"차가 빠졌어요. 다리의 빈 곳을 이어 보세요.");return}}}
function drawCloud(x,y,s){ctx.fillStyle="rgba(255,255,255,.82)";ctx.beginPath();ctx.arc(x,y,24*s,0,TAU);ctx.arc(x+25*s,y-7*s,19*s,0,TAU);ctx.arc(x+49*s,y,23*s,0,TAU);ctx.fill()}
function drawBackground(){var b=banks(),g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#8fd3ff");g.addColorStop(.68,"#e2f7ff");g.addColorStop(1,"#d8eef3");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawCloud(85,105,1);drawCloud(350,135,.86);drawCloud(675,100,1);drawCloud(980,130,.9);ctx.fillStyle="#7cab6f";ctx.beginPath();ctx.arc(390,470,150,Math.PI,0);ctx.arc(790,475,130,Math.PI,0);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();ctx.fill();ctx.fillStyle="#7b5b42";ctx.fillRect(0,b.y,b.leftX,H-b.y);ctx.fillRect(b.rightX,b.y,W-b.rightX,H-b.y);ctx.fillStyle="#5eb45f";ctx.fillRect(0,b.y-10,b.leftX,10);ctx.fillRect(b.rightX,b.y-10,W-b.rightX,10);ctx.fillStyle="#2b9be8";ctx.fillRect(b.leftX,b.waterY,b.rightX-b.leftX,H-b.waterY);ctx.strokeStyle="rgba(255,255,255,.42)";ctx.lineWidth=2;for(var yy=b.waterY+15;yy<H;yy+=17){ctx.beginPath();ctx.moveTo(b.leftX+5,yy);for(var xx=b.leftX+5;xx<b.rightX-10;xx+=30)ctx.quadraticCurveTo(xx+10,yy-5,xx+21,yy);ctx.stroke()}drawAnchor(b.leftAnchor);drawAnchor(b.rightAnchor)}
function drawAnchor(a){ctx.fillStyle="#3d4b5e";ctx.fillRect(a.x-18,a.y,36,22);ctx.fillStyle="#ffd34e";ctx.strokeStyle="#806300";ctx.lineWidth=3;ctx.beginPath();ctx.arc(a.x,a.y,9,0,TAU);ctx.fill();ctx.stroke()}
function drawBridge(){for(var i=0;i<S.edges.length;i++){var e=S.edges[i],strain=e.strain||1;if(e.broken){ctx.strokeStyle="rgba(255,92,109,.35)";ctx.setLineDash([8,7]);ctx.lineWidth=5}else{ctx.setLineDash([]);ctx.strokeStyle=strain<1.06?"#56697f":strain<1.11?"#5caeff":"#ffb44e";ctx.lineWidth=8}ctx.lineCap="round";ctx.beginPath();ctx.moveTo(e.a.x,e.a.y);ctx.lineTo(e.b.x,e.b.y);ctx.stroke();ctx.setLineDash([])}for(var j=0;j<S.nodes.length;j++){var n=S.nodes[j];ctx.fillStyle=n.pinned?"#ffd34e":"#41566e";ctx.beginPath();ctx.arc(n.x,n.y,n.pinned?6:3.2,0,TAU);ctx.fill()}}
function drawVehicle(){var v=S.vehicle;if(!v)return;ctx.save();ctx.translate(v.x,v.y);ctx.fillStyle="#ef4f55";ctx.fillRect(-v.w/2,-v.h/2,v.w,v.h);ctx.fillStyle="#dbeafe";ctx.fillRect(-8,-v.h/2-9,18,10);ctx.fillStyle="#152033";ctx.beginPath();ctx.arc(-17,v.h/2,8,0,TAU);ctx.arc(17,v.h/2,8,0,TAU);ctx.fill();ctx.restore()}
function fitCanvas(){var wrap=canvas.parentElement,r=wrap.getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H);canvas.style.width=Math.floor(W*scale)+"px";canvas.style.height=Math.floor(H*scale)+"px"}
function render(){ctx.clearRect(0,0,W,H);drawBackground();drawBridge();drawVehicle()}
function tick(now){var dt=Math.min(.033,Math.max(.001,(now-S.last)/1000));S.last=now;physics(dt);render();requestAnimationFrame(tick)}
function changeLevel(d){if(S.mode==="run")return;S.level=(S.level+d+LEVELS.length)%LEVELS.length;resetLevel()}
canvas.addEventListener("pointerdown",function(e){e.preventDefault();if(canvas.setPointerCapture)canvas.setPointerCapture(e.pointerId);startStroke(pointFromEvent(e))});
canvas.addEventListener("pointermove",function(e){if(!S.drawing)return;e.preventDefault();extendStroke(pointFromEvent(e))});
["pointerup","pointercancel","lostpointercapture"].forEach(function(type){canvas.addEventListener(type,function(e){if(S.drawing){e.preventDefault();endStroke()}})});
el.test.addEventListener("click",startTest);el.undo.addEventListener("click",undo);el.reset.addEventListener("click",clearAll);el.retry.addEventListener("click",resetLevel);
el.cont.addEventListener("click",function(){S.level=(S.level+1)%LEVELS.length;resetLevel()});el.prev.addEventListener("click",function(){changeLevel(-1)});el.next.addEventListener("click",function(){changeLevel(1)});
el.help.addEventListener("click",function(){el.tutorial.classList.remove("hidden")});el.tutorialClose.addEventListener("click",function(){el.tutorial.classList.add("hidden");try{localStorage.setItem("kidscade_bridge_scribble_help_v1","1")}catch(_){}});
window.addEventListener("resize",fitCanvas);try{window.KidscadeGame?.registerPauseHandlers?.({pause:function(){},resume:function(){S.last=performance.now()}})}catch(_){}
resetLevel();fitCanvas();var seen=false;try{seen=localStorage.getItem("kidscade_bridge_scribble_help_v1")==="1"}catch(_){}if(!seen)el.tutorial.classList.remove("hidden");requestAnimationFrame(tick);
})();