import { allowedWordchainInitials, dictionaryLookup, hasContinuation, nickname } from './wordchain-match.mjs';

const TURN_MS=12000,START_DELAY_MS=3000,ROOM_TTL_MS=45*60*1000;
const STARTERS=Object.freeze(['사과','기차','나무','바다','학교','토끼','고래','우산','친구','공원','자동차','강아지','시장','노래','과일','도서관','여행','운동장','사진','가방','구름','선물','수박','지도','호수','음악','그림','바람','공책','계단']);
const json=(body,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}});
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
async function hash(v){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v)))),b=>b.toString(16).padStart(2,'0')).join('')}
function fail(message,status=409,data={}){const e=new Error(message);e.status=status;e.data=data;throw e}
const iso=ms=>new Date(ms).toISOString();
function safeWord(v){return String(v||'').normalize('NFC').replace(/[\s·ㆍ・\-]/g,'').trim().slice(0,24)}
function hangulWord(v){const a=[...safeWord(v)];return a.length>=2&&a.length<=24&&a.every(ch=>{const n=ch.codePointAt(0);return n>=0xac00&&n<=0xd7a3})}
function actionId(v){const s=String(v||'').trim().slice(0,80);return /^[A-Za-z0-9_-]{8,80}$/.test(s)?s:''}
function minPlayers(s){return s.maxPlayers>2?3:2}
function alive(s){return s.players.filter(p=>p.lives>0&&!p.finishedAt)}
function nextAliveSlot(s,slot){const a=alive(s).sort((x,y)=>x.slot-y.slot);if(!a.length)return null;return (a.find(p=>p.slot>slot)||a[0]).slot}
function pushHistory(s,e){s.history=[...s.history,e].slice(-120)}
function starter(seed,turn,used){const start=Math.abs((Number(seed)||1)+(Number(turn)||0)*17)%STARTERS.length;for(let i=0;i<STARTERS.length;i++){const w=STARTERS[(start+i)%STARTERS.length];if(!used.has(w))return w}return STARTERS[start]}
function randomSeed(){const a=new Uint32Array(1);crypto.getRandomValues(a);return Number(a[0]&0x7fffffff)||1}
function snapshot(s,auth,ctx){
 const connected=new Set(ctx.getWebSockets().map(ws=>{try{return ws.deserializeAttachment()?.id}catch{return null}}));
 const players=s.players.map(p=>({slot:p.slot,nickname:p.nickname,ready:p.ready,lives:p.lives,eliminated:p.lives<=0||!!p.finishedAt,online:connected.has(p.id)||p.id===auth.id,isSelf:p.id===auth.id,isHost:p.id===s.hostId}));
 const self=players.find(p=>p.isSelf)||null;let result=null;if(s.status==='finished'){let outcome='draw';if(s.winnerId===auth.id)outcome='win';else if(s.winnerId)outcome='lose';result={outcome,winnerNickname:s.winnerId?s.players.find(p=>p.id===s.winnerId)?.nickname||null:null}}
 return {id:s.code,code:s.code,gameId:'wordchain_arena',transport:'v2',status:s.status,maxPlayers:s.maxPlayers,minPlayers:minPlayers(s),playerCount:s.players.length,serverNow:iso(Date.now()),startAt:s.startAt?iso(s.startAt):null,isHost:auth.id===s.hostId,self,players,canStart:auth.id===s.hostId&&s.status==='waiting'&&s.players.length>=minPlayers(s)&&s.players.every(p=>p.ready),match:{currentWord:s.currentWord,currentSlot:s.currentSlot,turnNo:s.turnNo,turnDeadline:s.deadlineAt?iso(s.deadlineAt):null,required:s.currentWord?allowedWordchainInitials([...s.currentWord].at(-1),true):[],history:s.history.slice(-60)},result}
}
function finish(s,winnerId,now){s.status='finished';s.winnerId=winnerId||null;s.currentSlot=null;s.deadlineAt=null;s.expiresAt=now+10*60*1000;s.version++}
function timeout(s,now){
 if(s.status!=='playing'||!s.deadlineAt||now<s.deadlineAt||now<(s.startAt||0))return false;
 const p=s.players.find(x=>x.slot===s.currentSlot);if(!p)return false;p.lives=Math.max(0,p.lives-1);if(!p.lives)p.finishedAt=p.finishedAt||now;
 pushHistory(s,{kind:'timeout',slot:p.slot,nickname:p.nickname,lostLife:1,turn:s.turnNo,at:iso(now)});const a=alive(s);
 if(a.length<=1)finish(s,a[0]?.id||null,now);else{s.currentSlot=nextAliveSlot(s,p.slot);s.turnNo++;s.deadlineAt=now+TURN_MS;s.version++}return true
}
export class WordchainRoom{
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.state=null;this.queue=Promise.resolve();this.ready=ctx.blockConcurrencyWhile(async()=>{this.state=await ctx.storage.get('room')||null});if(typeof WebSocketRequestResponsePair!=='undefined')ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping','pong'))}
 serial(fn){const p=this.queue.then(async()=>{await this.ready;return fn()});this.queue=p.catch(()=>{});return p}
 async commit(s){this.state=s;await this.ctx.storage.put('room',s);const times=[s.expiresAt];if(s.status==='playing'&&s.deadlineAt)times.push(s.deadlineAt);await this.ctx.storage.setAlarm(Math.max(Date.now()+50,Math.min(...times)))}
 broadcast(){for(const ws of this.ctx.getWebSockets())try{const a=ws.deserializeAttachment();if(a)ws.send(JSON.stringify({type:'state',room:snapshot(this.state,a,this.ctx)}))}catch{try{ws.close(1011,'send_failed')}catch{}}}
 async due(){if(!this.state)return;const now=Date.now();if(now>=this.state.expiresAt){for(const ws of this.ctx.getWebSockets())try{ws.close(1000,'room_expired')}catch{};await this.ctx.storage.deleteAll();this.state=null;return}if(timeout(this.state,now)){await this.commit(this.state);this.broadcast()}}
 async auth(request){const raw=(request.headers.get('authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(raw))fail('not_room_participant',403);const h=await hash(raw),p=this.state?.players.find(x=>x.tokenHash===h);if(!p)fail('not_room_participant',403);return{id:p.id,slot:p.slot,role:p.id===this.state.hostId?'host':'player'}}
 fetch(request){return this.serial(async()=>{try{return await this.handle(request)}catch(e){return json({ok:false,error:e.status?e.message:'multiplayer_internal_error',...(e.data||{})},e.status||500)}})}
 async handle(request){
  const url=new URL(request.url),action=url.pathname.split('/').pop(),body=request.method==='POST'?await request.json():{},now=Date.now();await this.due();
  if(action==='rooms'){if(this.state)fail('room_exists');const id=request.headers.get('x-kc-student-id'),name=nickname(request.headers.get('x-kc-nickname'));if(!id)fail('not_authenticated',401);const participantToken=token(),maxPlayers=Math.max(2,Math.min(8,Math.floor(Number(body.maxPlayers)||2)));const s={code:url.searchParams.get('code'),seed:randomSeed(),status:'waiting',maxPlayers,hostId:id,winnerId:null,startAt:null,currentWord:'',currentSlot:null,turnNo:0,deadlineAt:null,history:[],usedWords:[],players:[{id,slot:1,nickname:name,ready:true,lives:3,finishedAt:null,tokenHash:await hash(participantToken)}],actions:{},version:1,expiresAt:now+ROOM_TTL_MS,tickets:{}};await this.commit(s);return json({ok:true,transport:'v2',participantToken,room:snapshot(s,{id,slot:1,role:'host'},this.ctx)},201)}
  if(!this.state)fail('room_not_found',404);
  if(action==='join'){const id=request.headers.get('x-kc-student-id'),name=nickname(request.headers.get('x-kc-nickname'));if(!id)fail('not_authenticated',401);let p=this.state.players.find(x=>x.id===id);const participantToken=token();if(p){p.tokenHash=await hash(participantToken)}else{if(this.state.status!=='waiting')fail('room_already_started');if(this.state.players.length>=this.state.maxPlayers)fail('room_full');const occupied=new Set(this.state.players.map(x=>x.slot));let slot=1;while(occupied.has(slot))slot++;for(const x of this.state.players)x.ready=false;p={id,slot,nickname:name,ready:false,lives:3,finishedAt:null,tokenHash:await hash(participantToken)};this.state.players.push(p)}this.state.version++;await this.commit(this.state);this.broadcast();return json({ok:true,transport:'v2',participantToken,reconnected:!!this.state.players.find(x=>x.id===id),room:snapshot(this.state,{id,slot:p.slot,role:id===this.state.hostId?'host':'player'},this.ctx)},201)}
  if(action==='socket')return this.connect(request);const auth=await this.auth(request);
  if(action==='state')return json({ok:true,room:snapshot(this.state,auth,this.ctx)});
  if(action==='ticket'){const t=token();this.state.tickets[auth.id]={hash:await hash(t),expiresAt:now+60000,auth};await this.commit(this.state);return json({ok:true,ticket:t,expiresIn:60})}
  if(action==='heartbeat')return json({ok:true,wrote:false});
  const p=this.state.players.find(x=>x.id===auth.id);
  if(action==='ready'){if(this.state.status!=='waiting')fail('room_already_started');p.ready=body.ready!==false;this.state.version++;await this.commit(this.state);this.broadcast();return json({ok:true,room:snapshot(this.state,auth,this.ctx)})}
  if(action==='start'){if(auth.id!==this.state.hostId)fail('host_only',403);if(this.state.status!=='waiting')fail('room_already_started');if(this.state.players.length<minPlayers(this.state))fail('not_enough_players');if(!this.state.players.every(x=>x.ready))fail('players_not_ready');const used=new Set(),word=starter(this.state.seed,0,used);used.add(word);for(const x of this.state.players){x.lives=3;x.finishedAt=null}this.state.status='playing';this.state.startAt=now+START_DELAY_MS;this.state.currentWord=word;this.state.currentSlot=[...this.state.players].sort((a,b)=>a.slot-b.slot)[Math.abs(this.state.seed)%this.state.players.length].slot;this.state.turnNo=0;this.state.deadlineAt=this.state.startAt+TURN_MS;this.state.usedWords=[word];this.state.history=[{kind:'starter',word,turn:0,at:iso(now)}];this.state.version++;await this.commit(this.state);this.broadcast();return json({ok:true,room:snapshot(this.state,auth,this.ctx)})}
  if(action==='submit'){const aid=actionId(body.actionId);if(!aid)fail('invalid_action',400);const old=this.state.actions[aid];if(old&&old.playerId===auth.id)return json(old.response);await this.due();if(!this.state||this.state.status!=='playing')fail('match_not_playing');if(now<(this.state.startAt||0))fail('match_not_started');if(p.lives<=0||p.finishedAt)fail('player_eliminated');if(p.slot!==this.state.currentSlot)fail('not_your_turn');const word=safeWord(body.word);if(!hangulWord(word))fail('invalid_hangul_word',400);const required=allowedWordchainInitials([...this.state.currentWord].at(-1),true);if(!required.includes([...word][0]))fail('wrong_initial',422,{required});const used=new Set(this.state.usedWords);if(used.has(word))fail('already_used');const lookup=await dictionaryLookup(request,this.env,word);if(lookup.blocked)fail('word_not_allowed',422);if(!lookup.exists)fail('word_not_found',404);used.add(word);const turn=this.state.turnNo+1;pushHistory(this.state,{kind:'word',word,slot:p.slot,nickname:p.nickname,turn,at:iso(now)});let next=nextAliveSlot(this.state,p.slot),nextWord=word,oneShot=false;if(!(await hasContinuation(request,this.env,word,used))&&alive(this.state).length>1&&next!=null){oneShot=true;const victim=this.state.players.find(x=>x.slot===next);victim.lives=Math.max(0,victim.lives-1);if(!victim.lives)victim.finishedAt=now;pushHistory(this.state,{kind:'one-shot',slot:victim.slot,nickname:victim.nickname,lostLife:1,turn,at:iso(now)});const a=alive(this.state);if(a.length<=1)finish(this.state,a[0]?.id||null,now);else{nextWord=starter(this.state.seed,turn,used);used.add(nextWord);next=victim.lives?victim.slot:nextAliveSlot(this.state,victim.slot);pushHistory(this.state,{kind:'starter',word:nextWord,turn,at:iso(now)})}}if(this.state.status==='playing'){this.state.currentWord=nextWord;this.state.currentSlot=next;this.state.turnNo=turn;this.state.deadlineAt=now+TURN_MS;this.state.version++}this.state.usedWords=[...used];const response={ok:true,accepted:true,oneShot,room:snapshot(this.state,auth,this.ctx)};this.state.actions[aid]={playerId:auth.id,response};for(const key of Object.keys(this.state.actions).slice(0,-128))delete this.state.actions[key];await this.commit(this.state);this.broadcast();return json(response)}
  if(action==='leave'){if(this.state.status==='waiting'&&auth.id===this.state.hostId){for(const ws of this.ctx.getWebSockets())try{ws.close(1000,'host_left')}catch{};await this.ctx.storage.deleteAll();this.state=null;return json({ok:true,left:true})}if(this.state.status==='waiting'){this.state.players=this.state.players.filter(x=>x.id!==auth.id);for(const x of this.state.players)x.ready=false;this.state.version++;await this.commit(this.state);this.broadcast();return json({ok:true,left:true})}if(this.state.status==='playing'){p.lives=0;p.finishedAt=p.finishedAt||now;pushHistory(this.state,{kind:'leave',slot:p.slot,nickname:p.nickname,turn:this.state.turnNo,at:iso(now)});const a=alive(this.state);if(a.length<=1)finish(this.state,a[0]?.id||null,now);else if(this.state.currentSlot===p.slot){this.state.currentSlot=nextAliveSlot(this.state,p.slot);this.state.turnNo++;this.state.deadlineAt=now+TURN_MS;this.state.version++}await this.commit(this.state);this.broadcast()}return json({ok:true,left:true})}
  fail('not_found',404)
 }
 async connect(request){const url=new URL(request.url);if(request.headers.get('origin')!==url.origin)fail('invalid_origin',403);if((request.headers.get('upgrade')||'').toLowerCase()!=='websocket')fail('websocket_required',426);const raw=url.searchParams.get('ticket')||'',h=await hash(raw),entry=Object.entries(this.state.tickets).find(([,x])=>x.hash===h&&x.expiresAt>Date.now());if(!entry)fail('not_room_participant',403);const[id,{auth}]=entry;delete this.state.tickets[id];await this.commit(this.state);for(const old of this.ctx.getWebSockets())if(old.deserializeAttachment()?.id===id)try{old.close(4001,'replaced')}catch{}const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({...auth,lastSyncAt:Date.now()});server.send(JSON.stringify({type:'state',room:snapshot(this.state,auth,this.ctx)}));return new Response(null,{status:101,webSocket:client})}
 webSocketMessage(ws,msg){return this.serial(async()=>{const a=ws.deserializeAttachment();if(msg!=='sync'||!a){ws.close(1008,'invalid_message');return}if(Date.now()-a.lastSyncAt<2000)return;a.lastSyncAt=Date.now();ws.serializeAttachment(a);await this.due();if(this.state)ws.send(JSON.stringify({type:'state',room:snapshot(this.state,a,this.ctx)}))})}
 webSocketClose(ws,code){try{ws.close(code===1006?1000:code)}catch{}} webSocketError(ws){try{ws.close(1011,'connection_error')}catch{}}
 alarm(){return this.serial(async()=>{await this.due();if(this.state)await this.commit(this.state)})}
}
