(()=>{'use strict';
const $=id=>document.getElementById(id),{elements}=PeriodicData,KEY='kidscade.periodic.v1';
let saved={known:[],wrong:[],best:{},rainBestCombo:0,rainBestScore:0},limit=20,audio=true,ctx=null,mode='home';
let active=[],raf=0,lastFrame=0,lastSpawn=0,startAt=0,duration=60,score=0,combo=0,maxCombo=0,lives=5,hit=0,miss=0,rainRunning=false,oneLetterTimer=0;
let puzzleQueue=[],puzzleIndex=0,puzzleCorrect=0,puzzleStarted=0,puzzleLocked=false,lastCompleted='rain';
try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p&&typeof p==='object')saved=Object.assign(saved,p);}catch{}
if(!Array.isArray(saved.known))saved.known=[];if(!Array.isArray(saved.wrong))saved.wrong=[];if(!saved.best||typeof saved.best!=='object')saved.best={};
const shuffle=a=>[...a].sort(()=>Math.random()-.5),pool=()=>elements.filter(e=>e.number<=limit);
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}}
function sdk(m,d){try{window.KidscadeGame?.[m]?.(d);}catch{}}
function tone(freq=600,d=.08){if(!audio)return;try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=freq;g.gain.setValueAtTime(.06,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.start();o.stop(ctx.currentTime+d+.02);}catch{}}
function view(id){for(const x of ['home','reference','rain','study','puzzleView','result']){const el=$(x);if(!el)continue;if(x==='home')el.style.display=id==='home'?'grid':'none';else el.classList.toggle('active',x===id);if(x==='reference')el.hidden=id!=='reference';}mode=id;}
function setLimit(){limit=Number($('range').value)||20;}
function home(){stopRain(false);setLimit();view('home');$('knownCount').textContent=saved.known.length+' / 118';$('bestCombo').textContent=saved.rainBestCombo||0;$('reviewStart').disabled=!saved.wrong.length;}
function makeCell(e,puzzle){const b=document.createElement('button');b.className='cell';b.style.gridArea=`${e.row} / ${e.col}`;if(puzzle){const inScope=puzzleQueue.some(x=>x.number===e.number),done=puzzleQueue.slice(0,puzzleIndex).some(x=>x.number===e.number);if(done)b.classList.add('done');if(!inScope)b.classList.add('outside');b.disabled=!inScope||done;b.innerHTML=`<small>${e.number}</small><b>${done?e.symbol:'?'}</b><small>${done?e.name:''}</small>`;b.onclick=()=>answerPuzzle(e,b);}else{if(saved.known.includes(e.number))b.classList.add('done');b.innerHTML=`<small>${e.number}</small><b>${e.symbol}</b><small>${e.name}</small>`;b.title=e.aliases?.length?e.aliases.join(', '):e.name;}return b;}
function renderReference(){const t=$('referenceTable');t.replaceChildren();elements.forEach(e=>t.append(makeCell(e,false)));}
function study(review=false){stopRain(false);setLimit();view('study');const list=review?elements.filter(e=>saved.wrong.includes(e.number)):pool();$('cards').replaceChildren();if(!list.length){home();return}list.forEach(e=>{const b=document.createElement('button');let hidden=false;const draw=()=>{b.innerHTML=`<small>${e.number}번</small><b>${hidden?'?':e.symbol}</b><span>${e.name}</span><small>${hidden?'눌러서 확인':'눌러서 가리기'}</small>`;};b.onclick=()=>{hidden=!hidden;draw()};draw();$('cards').append(b);});}
function startPuzzle(){stopRain(false);setLimit();puzzleQueue=shuffle(pool());puzzleIndex=0;puzzleCorrect=0;puzzleStarted=performance.now();view('puzzleView');sdk('start',{mode:'table',range:limit});renderPuzzle();}
function renderPuzzle(){if(puzzleIndex>=puzzleQueue.length){finishPuzzle();return}puzzleLocked=false;const e=puzzleQueue[puzzleIndex];$('puzzleHud').textContent=`${puzzleIndex+1} / ${puzzleQueue.length} · 정답 ${puzzleCorrect}`;$('puzzlePrompt').innerHTML=`<b>${e.symbol}</b> · ${e.name}이 들어갈 자리를 눌러 보세요`;$('puzzleFeedback').textContent='';const t=$('puzzleTable');t.replaceChildren();elements.forEach(x=>t.append(makeCell(x,true)));}
function answerPuzzle(chosen,button){if(puzzleLocked)return;const e=puzzleQueue[puzzleIndex];if(!e)return;puzzleLocked=true;const ok=chosen.number===e.number;tone(ok?800:180,.12);if(ok){puzzleCorrect++;if(!saved.known.includes(e.number))saved.known.push(e.number);saved.wrong=saved.wrong.filter(n=>n!==e.number);button.classList.add('done');$('puzzleFeedback').textContent='✨ 정답! '+e.number+'번 '+e.name+' = '+e.symbol;}else{if(!saved.wrong.includes(e.number))saved.wrong.push(e.number);button.classList.add('target');$('puzzleFeedback').textContent='아쉬워요. '+e.name+'의 자리를 다시 기억해 봐요.';}persist();puzzleIndex++;setTimeout(renderPuzzle,420);}
function finishPuzzle(){lastCompleted='table';const pct=Math.round(puzzleCorrect/Math.max(1,puzzleQueue.length)*100);sdk('result',{scope:'session',status:'completed',outcome:puzzleCorrect===puzzleQueue.length?'win':'neutral',score:pct,scoreOptions:{higherIsBetter:true,unit:'percent'},mode:'table',range:limit,correct:puzzleCorrect,total:puzzleQueue.length,perfectTable:limit===118&&puzzleCorrect===118,seconds:Math.round((performance.now()-puzzleStarted)/1000)});$('resultTitle').textContent='🧩 주기율표 채우기 완료';$('resultScore').textContent=puzzleCorrect+' / '+puzzleQueue.length;$('resultNote').textContent='정답률 '+pct+'%';$('resultReview').disabled=!saved.wrong.length;view('result');}

function clearCards(){active.forEach(o=>o.el.remove());active=[];}
function spawnCard(now){const choices=pool();if(!choices.length)return;let e=choices[Math.floor(Math.random()*choices.length)];if(active.length<choices.length){for(let tries=0;tries<8&&active.some(o=>o.e.number===e.number);tries++)e=choices[Math.floor(Math.random()*choices.length)];}
const field=$('rainField'),w=field.clientWidth||600,cardW=w<430?92:108,lanes=Math.max(2,Math.floor((w-16)/(cardW+8))),counts=Array(lanes).fill(0);active.forEach(o=>{if(o.lane<lanes)counts[o.lane]++});let min=Math.min(...counts),opts=counts.map((v,i)=>v===min?i:-1).filter(i=>i>=0),lane=opts[Math.floor(Math.random()*opts.length)],gap=(w-cardW)/Math.max(1,lanes-1),x=lanes===1?8:Math.max(4,Math.min(w-cardW-4,lane*gap));
const el=document.createElement('div');el.className='fall-card';el.innerHTML=`<span class="num">${e.number}번</span><b>${e.name}</b><span class="mystery">?</span>`;field.append(el);
const elapsed=(now-startAt)/1000,speed=38+Math.min(42,elapsed*.55)+Math.random()*8;active.push({e,el,x,y:-90,speed,lane});}
function updateCard(o){const p=`translate(${o.x}px,${o.y}px)`;o.el.style.setProperty('--pos',p);o.el.style.transform=p;}
function refreshRainHud(remain){$('timerChip').textContent=Math.max(0,Math.ceil(remain))+'초';$('scoreChip').textContent=score+'점';$('comboChip').textContent=combo+' COMBO';$('comboBig').textContent=combo;$('lives').textContent='❤️'.repeat(lives)+'🖤'.repeat(Math.max(0,5-lives));}
function highlightPrefix(v){active.forEach(o=>o.el.classList.toggle('target',!!v&&o.e.symbol.toLowerCase().startsWith(v.toLowerCase())));}
function tick(now){if(!rainRunning)return;if(!lastFrame)lastFrame=now;const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;const elapsed=(now-startAt)/1000,remain=duration-elapsed;
const interval=Math.max(650,1450-elapsed*10);if(now-lastSpawn>interval){spawnCard(now);lastSpawn=now}
const bottom=($('rainField').clientHeight||560)-72;for(let i=active.length-1;i>=0;i--){const o=active[i];o.y+=o.speed*dt;updateCard(o);if(o.y>bottom){active.splice(i,1);o.el.classList.add('miss');setTimeout(()=>o.el.remove(),330);miss++;combo=0;lives--;if(!saved.wrong.includes(o.e.number))saved.wrong.push(o.e.number);tone(150,.15);$('rainHint').textContent=`${o.e.name} = ${o.e.symbol} 였어요!`;persist();if(lives<=0){finishRain();return}}}
refreshRainHud(remain);if(remain<=0){finishRain();return}raf=requestAnimationFrame(tick);}
function hitCard(o){const idx=active.indexOf(o);if(idx<0)return;active.splice(idx,1);hit++;combo++;maxCombo=Math.max(maxCombo,combo);score+=100+Math.min(500,(combo-1)*25);if(!saved.known.includes(o.e.number))saved.known.push(o.e.number);saved.wrong=saved.wrong.filter(n=>n!==o.e.number);saved.rainBestCombo=Math.max(saved.rainBestCombo||0,maxCombo);saved.rainBestScore=Math.max(saved.rainBestScore||0,score);persist();o.el.querySelector('.mystery').textContent=o.e.symbol;o.el.classList.remove('target');o.el.classList.add('hit');tone(560+Math.min(420,combo*22),.08);setTimeout(()=>o.el.remove(),320);$('rainInput').value='';$('rainHint').textContent=`✨ ${o.e.name} = ${o.e.symbol} · ${combo} 콤보!`;highlightPrefix('');refreshRainHud(duration-(performance.now()-startAt)/1000);}
function tryMatch(value,forceOne=false){const v=value.trim().toLowerCase();clearTimeout(oneLetterTimer);if(!v){highlightPrefix('');return}highlightPrefix(v);const exact=active.filter(o=>o.e.symbol.toLowerCase()===v).sort((a,b)=>b.y-a.y)[0];if(exact){const hasLonger=active.some(o=>o.e.symbol.length>v.length&&o.e.symbol.toLowerCase().startsWith(v));if(v.length===1&&hasLonger&&!forceOne){oneLetterTimer=setTimeout(()=>tryMatch(v,true),220);return}hitCard(exact);return}
const possible=active.some(o=>o.e.symbol.toLowerCase().startsWith(v));if(!possible){tone(220,.04);$('rainInput').classList.add('bad');setTimeout(()=>{$('rainInput').classList.remove('bad');if($('rainInput').value.trim().toLowerCase()===v){$('rainInput').value='';highlightPrefix('')}},160);}}
function startRain(){setLimit();stopRain(false);score=combo=maxCombo=hit=miss=0;lives=5;rainRunning=true;startAt=performance.now();lastFrame=lastSpawn=0;clearCards();view('rain');$('rainInput').value='';$('rainHint').textContent='원소 이름을 보고 기호를 입력하세요!';refreshRainHud(duration);sdk('start',{mode:'rain',range:limit});setTimeout(()=>$('rainInput').focus({preventScroll:true}),40);raf=requestAnimationFrame(tick);}
function stopRain(abandoned=true){if(!rainRunning){cancelAnimationFrame(raf);return}rainRunning=false;cancelAnimationFrame(raf);clearTimeout(oneLetterTimer);if(abandoned)sdk('result',{scope:'session',status:'abandoned',mode:'rain',range:limit,score});clearCards();}
function finishRain(){if(!rainRunning)return;lastCompleted='rain';rainRunning=false;cancelAnimationFrame(raf);clearTimeout(oneLetterTimer);clearCards();saved.rainBestCombo=Math.max(saved.rainBestCombo||0,maxCombo);saved.rainBestScore=Math.max(saved.rainBestScore||0,score);persist();sdk('result',{scope:'session',status:'completed',outcome:lives>0?'win':'neutral',score,scoreOptions:{higherIsBetter:true,unit:'points'},mode:'rain',range:limit,correct:hit,total:hit+miss,maxCombo,misses:miss,seconds:Math.round((performance.now()-startAt)/1000)});$('resultTitle').textContent=lives>0?'🌧️ 원소비 생존 성공!':'🧪 실험실이 가득 찼어요!';$('resultScore').textContent=score+'점';$('resultNote').textContent=`정답 ${hit}개 · 놓침 ${miss}개 · 최대 ${maxCombo} 콤보 · 최고 점수 ${saved.rainBestScore||score}점`;$('resultReview').disabled=!saved.wrong.length;view('result');}

$('rainInput').addEventListener('input',e=>tryMatch(e.target.value));
$('rainInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();tryMatch(e.currentTarget.value,true)}});
$('rainStart').onclick=startRain;$('studyStart').onclick=()=>study(false);$('tableStart').onclick=startPuzzle;$('reviewStart').onclick=()=>study(true);$('resultReview').onclick=()=>study(true);$('retry').onclick=()=>lastCompleted==='table'?startPuzzle():startRain;
$('toggleReference').onclick=()=>{stopRain(false);renderReference();view('reference')};
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>{if(mode==='rain')stopRain(true);home()});
$('sound').onclick=()=>{audio=!audio;$('sound').textContent=audio?'🔊':'🔇';if(audio)tone(720,.06)};
window.addEventListener('resize',()=>{if(!rainRunning)return;active.forEach(o=>{o.x=Math.min(o.x,Math.max(4,$('rainField').clientWidth-112));updateCard(o)})});
renderReference();home();
})();